### ISSUE TITLE
[lately][func] 앱에서 녹화 시작 할 경우 해당 기기가 까만 화면만 보임

### ISSUE THREAD

**Issue by jangyoojin** [vmeeting-io/vmeeting_issue#102]
[발생현상]
안드로이드 앱 사용자가 방장일 때, 녹화 시작을 하면 5초 정도 녹화 되다가 기기의 화면이 검정색으로 보입니다.

[발생일자]
2021.08.03

[재현경로]
- 발생 환경 : 안드로이드 앱
1. 안드로이드 앱으로 로그인하여 회의 생성
2. 방장 권한을 가진 상태에서 녹화 시작 버튼 클릭
3. 잠시 기다리면 화면이 까맣게 변함

[스크린샷 및 동영상 첨부]
![image](https://user-images.githubusercontent.com/74976893/127963881-bfec1c3f-d4b3-46c6-9c80-a8265e5b4f06.png)

**Comment by jungheekang** [comment]
vmeeting-release-v21.2.0-build-3.apk
21.2.0 build 8166736 버전에서 발생

**Comment by theun0524** [comment]
vmeeting-release-v21.3.0-build-2.apk 에서 확인 후 close 부탁합니다.

**Comment by jangyoojin** [comment]
vmeeting-release-v21.3.0-build-2.apk에서 녹화 시작 버튼이 보이지 않습니다. 확인 불가합니다.

**Comment by jangyoojin** [comment]
vmeeting-release-v21.3.0-build-2.apk에서 녹화 기능이 정상동작함을 확인했습니다.
