### ISSUE TITLE
[lately][UI] 앱 가로모드에서 방 이름 입력 시 입력된 글씨가 표시되지 않음

### ISSUE THREAD

**Issue by ktm526** [vmeeting-io/vmeeting_issue#103]
[발생현상]
안드로이드 모바일 앱에서 화면을 가로로 설정한 뒤 앱을 키고 방 이름 입력란에 이름을 입력할 경우 글자가 표시되지 않습니다. (회의실 이동은 정상적으로 가능)

[발생일자]
2021.08.03

[재현경로]
- 발생 환경 : 안드로이드 모바일 app
1. 안드로이드 모바일 앱에서 화면을 가로로 전환
2. 회의실 이름 입력

[스크린샷 및 동영상 첨부]

![ezgif com-gif-maker](https://user-images.githubusercontent.com/77431608/128029835-66305dc2-23d1-4693-b5df-3057485e96cd.gif)

**Comment by sjhan22** [comment]
첨부해주신 동영상이 재생되지 않는 것 같습니다.

**Comment by ktm526** [comment]
> 첨부해주신 동영상이 재생되지 않는 것 같습니다.

gif 파일로 바꾸었습니다

**Comment by jungheekang** [comment]
바탕색과 글자 색상이 모두 하얀색이여서 안보이는것같습니다. 글자 색상을 연한 그레이색상으로 변경하면 좋을듯합니다.

**Comment by ktm526** [comment]
v21.3.0 (build 8299464)에서 해결되어 이슈 close 합니다
