### ISSUE TITLE
[lately][UI] 안드로이드 모바일 앱 가로모드에서 로그인 창에 아이디 및 비밀번호 입력이 불가능한 현상

### ISSUE THREAD

**Issue by ktm526** [vmeeting-io/vmeeting_issue#104]
[발생현상]
안드로이드 모바일 앱을 화면이 가로 상태인 환경에서 실행할 시, 로그인 창에 아이디 및 비밀번호를 입력하기 위해 입력칸을 터치할 경우 화면이 자동으로 새로고침 되면서 키보드가 꺼져 입력이 불가능합니다.

[발생일자]
2021.08.03

[재현경로]
- 발생 환경 : 안드로이드 모바일 앱
1. 모바일 앱 실행 후 화면을 가로로 전환
2. 로그인 하지 않은 상태에서 회의 생성 후 팝업창에서 확인 버튼 터치
3. 아이디 및 비밀번호 입력창 터치

[스크린샷 및 동영상 첨부]

![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/77431608/128030233-e27983b9-ab15-41ab-89de-4fd87a94f0d4.gif)

**Comment by jungheekang** [comment]
@ktm526 vmeeting-release-v21.2.0-build-3.apk (build 8166736)에서 발생된건가요?제가 해보니까 현상 재현이 안되서요 확인부탁드려요.

**Comment by ktm526** [comment]
> @ktm526 vmeeting-release-v21.2.0-build-3.apk (build 8166736)에서 발생된건가요?제가 해보니까 현상 재현이 안되서요 확인부탁드려요.

확인 결과 빌드3 apk에서도 동일하게 발생합니다. 내일 다른 안드로이드 모바일 기기로 추가 테스트 해보겠습니다.

**Comment by jangyoojin** [comment]
갤럭시S10 모델에서도 동일한 문제가 발생합니다

**Comment by theun0524** [comment]
vmeeting-release-v21.3.0-build-4.apk 로 테스트 부탁합니다.

**Comment by dmsgk724** [comment]
잘 작동하여 이슈를 close합니다
