### ISSUE TITLE
[lately][func] 회의실 내 참가자가 3명 이상일 경우, PC 브라우저에서 접속이 끊어지는 현상

### ISSUE THREAD

**Issue by SangY00n** [vmeeting-io/vmeeting_issue#105]
[발생현상]
회의실 내의 참가자가 3명 이상이 될 경우, PC 브라우저에서 접속한 참가자가 회의실에서 나가지거나 해당 참가자의 화면에 빈 화면(첨부사진)이 출력되는 현상이 발생합니다.

3명 이상이 되었을 때
- 기존에 회의실에 있었던 참가자: 회의실에서 나가짐
- 새로 접속한 참가자: 화면에 빈 화면이 출력됨

iOS 앱에서 접속한 참가자는 연결이 끊어지지 않습니다.

[발생일자]
2021.08.03

[재현경로]
- 발생 환경 : windowOS의 모든 브라우저
1. 회의실에 3명 이상 참가
2. PC 브라우저에서 접속한 참가자의 화면 확인 

[스크린샷 및 동영상 첨부]
![image](https://user-images.githubusercontent.com/85980653/127971297-3d934e77-1511-4f3c-bd36-c43d4bc5e79c.png)

**Comment by jangyoojin** [comment]
안드로이드 앱에서 접속한 참가자도 연결이 끊어지지 않습니다.

**Comment by jungheekang** [comment]
확인했습니다.
