### ISSUE TITLE
[lately][func] 앱에서 참여자 추가메뉴 중 음소거 기능 동작 안함

### ISSUE THREAD

**Issue by jangyoojin** [vmeeting-io/vmeeting_issue#107]
[발생현상]
앱에서 다른 참가자의 화면을 롱프레스하면 나오는 추가메뉴에서 음소거가 동작하지 않습니다. 아래 그림과 같이 [음소거] 버튼을 터치해도 아무런 반응이 없습니다.

[발생일자]
2021.08.04

[재현경로]
- 발생 환경 : 안드로이드 앱 (버전: vmeeting-release-v21.2.0-build-3)
1. 하나의 회의에 둘 이상의 사용자가 접속
2. 방장이 다른 사용자의 화면을 몇 초동안 터치
3. 추가메뉴의 음소거 버튼 터치

[스크린샷 및 동영상 첨부]
![image](https://user-images.githubusercontent.com/74976893/128122649-3e6a4ef0-f5d3-491a-80b8-272484ba2998.png)

**Comment by sjhan22** [comment]
IOS APP에서도 동일한 현상 발생합니다.

**Comment by SangY00n** [comment]
WindowOS의 모든 브라우저에서도 동일한 현상이 발생합니다. (참여자 추가메뉴 - 음소거 작동 안함)

**Comment by jangyoojin** [comment]
정상 동작하는 것을 확인했습니다.
