### ISSUE TITLE
[lately][UI] 품질 설정 후 회의화면 상단 품질 'AUD'로만 유지되는 현상

### ISSUE THREAD

**Issue by YoungRaeKimm** [vmeeting-io/vmeeting_issue#11]
[발생현상]
품질을 새롭게 설정 하였을 때에 회의화면 상단 'HD'나 'SD' 와 같은 품질이 'AUD'로 고정되는 현상입니다.

[발생일자]
2020-07-22
[재현경로]
- 발생 환경 : iPad OS safari
1. 품질설정을 바꿈
2. 아래의 'SD'로 바꿈에도 불구하고 위에 'AUD'로 고정되는 것을 확인하실 수 있습니다.
3. 

[스크린샷 및 동영상 첨부]
![IMG_0385](https://user-images.githubusercontent.com/33543992/126614328-e25dc371-84b0-466c-8e8f-13ec8b71cdd9.PNG)

**Comment by sjhan22** [comment]
아이폰 모든 브라우저에서도 동일한 현상 발생합니다. (코멘트 단 후에 issue는 close 합니다.)

**Comment by jungheekang** [comment]
안드로이드 - 모든 웹 브라우저에도 동일 발생
