### ISSUE TITLE
[lately][func] 참여자 추가메뉴 중 '카메라 끄기' 작동 안함

### ISSUE THREAD

**Issue by SangY00n** [vmeeting-io/vmeeting_issue#110]
[발생현상]
PC에서 방장 권한을 가지고 있는 참여자가 다른 참여자의 추가메뉴 중 '카메라 끄기'를 클릭하였을 때 아무런 반응이 없습니다.

[발생일자]
2021.08.04

[재현경로]
- 발생 환경 : windowOS 모든 브라우저
1. 참여자 추가메뉴(...) - 카메라 끄기
2. 반응 없음

[스크린샷 및 동영상 첨부]
![image](https://user-images.githubusercontent.com/85980653/128127868-c1600a59-2546-426d-8329-5f9b41c95200.png)

**Comment by jungheekang** [comment]
확인했습니다.
