### ISSUE TITLE
[lately][UI] 자신을 제외한 다른 회의 참여자들의 접속자 통계 상태가 비정상적으로 출력되는 현상

### ISSUE THREAD

**Issue by SangY00n** [vmeeting-io/vmeeting_issue#111]
[발생현상]
추가 액션(...) - 접속자 통계 메뉴에서
자신을 제외한 다른 회의 참여자들의 상태가 비정상적으로 출력됩니다.
자신(나)의 상태(status)만 정상적으로 출력되고 다른 참여자들의 상태(status)는 무조건 아래와 같이 출력됩니다.
![image](https://user-images.githubusercontent.com/85980653/128293694-d9a876fd-6276-4167-bfc3-f5ea2dd9ec21.png)

[발생일자]
2021.08.05

[재현경로]
- 발생 환경 : WindowOS의 모든 브라우저
1. 회의실에 2명 이상 참여
2. 추가 액션(...) - 접속자 통계

[스크린샷 및 동영상 첨부]
![image](https://user-images.githubusercontent.com/85980653/128293471-94e44755-afda-4f3c-83fe-7210d96c157a.png)

**Comment by huijjj** [comment]
수정하여 lately에 반영했습니다. 확인부탁드립니다.

**Comment by SangY00n** [comment]
확인하였습니다. 이슈 close 하겠습니다.
