### ISSUE TITLE
[lately][UI] 참가자 화면 하단에 사용자 이름과 음소거 표시가 겹치는 문제

### ISSUE THREAD

**Issue by jangyoojin** [vmeeting-io/vmeeting_issue#113]
[발생현상]
참가자 화면이 크게 보일 때, 우측에 보이는 참가자 화면에서 사용자 이름과 음소거 표시가 겹쳐 보입니다.(아래 그림 참고)
이때 방장 권한을 가진 참가자만 겹침 현상이 발생합니다.
[발생일자]
2021.08.05

[재현경로]
- 발생 환경 : 윈도우 모든 웹 브라우저
1. 방장 권한을 가진 참가자로 회의에 접속
2. 마이크와 카메라를 모두 끈 상태로 작은 참가자 화면 하단 관찰

[스크린샷 및 동영상 첨부]
![image](https://user-images.githubusercontent.com/74976893/128318334-4aac12bf-61f0-4e15-baa9-56cc23a27dd2.png)

**Comment by huijjj** [comment]
아이콘들을 세로로 배치하도록 lately에 수정하였습니다 확인 부탁드립니다.

**Comment by huijjj** [comment]
잘 동작하는 것을 확인했습니다
