### ISSUE TITLE
[lately][func] 방장 권한을 위임받은 참여자는 회의실 이름을 바꿀 수 없는 현상

### ISSUE THREAD

**Issue by SangY00n** [vmeeting-io/vmeeting_issue#114]
[발생현상]
기존의 방장으로부터 방장 권한을 위임받은 참여자는 회의실 이름을 바꿀 수 없습니다.

회의실 이름에 커서를 올려도 회의실 이름 편집 버튼이 뜨지 않습니다.

[발생일자]
2021.08.05

[재현경로]
- 발생 환경 : WindowOS의 모든 브라우저
1. 방장이 회의 참여자에게 방장 권한 위임
2. 방장 권한을 위임받은 회의 참여자가 회의실 이름 수정 시도 

[스크린샷 및 동영상 첨부]
회의실을 생성한 방장이 회의실 이름에 커서를 올렸을 때
![image](https://user-images.githubusercontent.com/85980653/128318996-a9f9cb86-2a56-4d12-86ee-f671f87b16cf.png)

방장 권한을 위임받은 참여자가 회의실 이름에 커서를 올렸을 때 (편집 버튼 뜨지 않음)
![image](https://user-images.githubusercontent.com/85980653/128319147-de3985f4-3300-46f9-9597-8226f7bbc337.png)

**Comment by huijjj** [comment]
수정하여 lately에 반영하였습니다, 확인 부탁드립니다

**Comment by SangY00n** [comment]
수정 확인하였습니다. 이슈 close 하겠습니다.
