### ISSUE TITLE
[lately][UI] 참가자뷰 숨기기, 보이기 버튼이 동작하지 않는 현상

### ISSUE THREAD

**Issue by YoungRaeKimm** [vmeeting-io/vmeeting_issue#115]
[발생현상]
참가자뷰 숨기기, 보이기 버튼이 동작하지 않는 현상

[발생일자]
2020-08-06

[재현경로]
- 발생 환경 : 아이패드 모든 브라우저
1.  토글뷰 off 상태에서 참가자뷰 숨기기, 보이기 버튼 누르기
2.
3.

[스크린샷 및 동영상 첨부]

**Comment by SangY00n** [comment]
아이폰의 모든 브라우저의 가로 모드에서도 동일하게 참가자뷰 숨기기, 보이기 버튼이 동작하지 않습니다.
아이폰의 모든 브라우저의 세로 모드에서는 정상적으로 동작합니다.

**Comment by YoungRaeKimm** [comment]
아이패드 모든 브라우저에서 다시 잘 작동되는 것으로 확인했습니다.
