### ISSUE TITLE
[lately][UI] 참가자 ...버튼 사라짐 현상

### ISSUE THREAD

**Issue by YoungRaeKimm** [vmeeting-io/vmeeting_issue#116]
[발생현상]
참가자 ...버튼이 사라졌습니다.

[발생일자]
2021-08-06

[재현경로]
- 발생 환경 : 아이패드 모든 브라우저
1. 
2.
3.

[스크린샷 및 동영상 첨부]
![IMG_9F8459107FBE-1](https://user-images.githubusercontent.com/33543992/128456801-fa1a311f-5867-43cc-8a11-e40e4666b0f7.jpeg)

**Comment by jungheekang** [comment]
모바일 web ,app 에서 발생
참여자 영상의 추가 메뉴(...버튼) 표출되지 않음.
