### ISSUE TITLE
[lately][UI] 참가자 목록 토글을 눌렀을 때 눌린 상태로 변하지 않는 현상

### ISSUE THREAD

**Issue by SangY00n** [vmeeting-io/vmeeting_issue#118]
[발생현상]
_참가자 목록_ 토글을 눌렀을 때 토글 버튼이 눌린 상태로 변하지 않습니다.

[발생일자]
2021.08.06

[재현경로]
- 발생 환경 : WindowOS의 모든 브라우저, iOS의 모든 브라우저
1. _참가자 목록_ 토글을 누른다.
2. 눌렀을 때의 토글 버튼이 변화하는지 확인한다.

[스크린샷 및 동영상 첨부]
_화면 공유_ 토글, _대화 열기_ 토글, _말하기 요청_ 토글, _타일뷰_ 토글과 달리
_참가자 목록_ 토글은 토글 버튼을 눌렀을 때 눌린 상태로 변하지 않습니다.
![Animation_2021-08-06-15-05-33](https://user-images.githubusercontent.com/85980653/128463983-0bc900a9-91c2-4d58-8061-fdaf61af3b68.gif)

**Comment by boonjo** [comment]
발생환경 macOS 모든 브라우저에서도 동일 현상 발생

**Comment by jungheekang** [comment]
첨부된 사진과 같이 참가자 목록이 활성화 되었을때 아이콘 백그라운드 추가 필요

<img width="173" alt="image" src="https://user-images.githubusercontent.com/87403323/128669864-bfcd6513-ac0b-4f94-bd4d-32ce6cd63b64.png">

**Comment by huijjj** [comment]
수정하여 lately에 반영했습니다 확인 부탁드립니다
