### ISSUE TITLE
[lately][UI] 타일뷰 상태에서 화면 상단에 품질 상태 보이지 않는 현상

### ISSUE THREAD

**Issue by YoungRaeKimm** [vmeeting-io/vmeeting_issue#119]
[발생현상]
타일뷰 상태에서 화면 상단에 품질 상태 보이지 않는 현상

[발생일자]
2021-08-06

[재현경로]
- 발생 환경 : 아이패드 모든 브라우저
1. 타일뷰 ON
2.
3.

[스크린샷 및 동영상 첨부]

https://user-images.githubusercontent.com/33543992/128469639-ba05b48e-05d7-4704-b30b-5816bd1a0d4a.MP4

**Comment by jungheekang** [comment]
이건 컨셉인것같아요... 타일뷰로 봤을때 다수여서 영상품질을 표시 할수없고, 특정 참가자을 선택했을때 그 참가자의 품질이 표시되는것같습니다.
