### ISSUE TITLE
[lately][func] 참석자 목록에서 참석인 음소거 작동 오류

### ISSUE THREAD

**Issue by boonjo** [vmeeting-io/vmeeting_issue#121]
[발생현상]

![mute](https://user-images.githubusercontent.com/61446495/128534779-7686ab81-a9c9-42c6-8280-ac4c77b362d3.gif)

[발생일자]

2021-08-07

[재현경로]
- 발생 환경 : macOS 모든 브라우저
1. 참가자 목록 열기
2. 참석인 더보기
3. 음소거

**Comment by jungheekang** [comment]
@sajan-dpnm  첨부된 사진의 빨강색 하이라이트 메뉴를 disable (hiden) 해주시면 될것같습니다.

<img width="216" alt="스크린샷 2021-08-09 오후 2 29 20" src="https://user-images.githubusercontent.com/87403323/128663992-f89d141d-4748-439b-b246-79a9f8f7a0ad.png">

**Comment by sajan-dpnm** [comment]
okay!

**Comment by sajan-dpnm** [comment]
코드 수정했습니다. 확인 부탁드립니다!
![image](https://user-images.githubusercontent.com/72065079/128671323-d2d2e22c-fa86-4c59-b80c-317225322d94.png)

**Comment by jungheekang** [comment]
@boonjo 이 문제 제가 확인했어요. close하겠습니다.
