### ISSUE TITLE
[lately][func] 배경선택에서 화면공유가 배경으로 적용되지 않는 문제

### ISSUE THREAD

**Issue by jangyoojin** [vmeeting-io/vmeeting_issue#122]
[발생현상]
배경 선택에서 화면공유를 배경으로 선택하면 공유한 화면이 배경으로 적용되지 않습니다. 아래 사진과 같이 화면을 공유 중이라는 팝업은 뜨지만 공유 중인 화면이 보이지 않습니다.

[발생일자]
2021.08.09

[재현경로]
- 발생 환경 : 윈도우 os 모든 웹 브라우저(크롬, 엣지, 네이버 웨일, 오페라)
1. 회의 생성
2. 배경 선택 - 화면공유 - 적용
3. 자신의 배경이 공유한 화면이 아니라 아무 배경도 없는 상태로 표시됨을 확인

[스크린샷 및 동영상 첨부]
![image](https://user-images.githubusercontent.com/74976893/128663030-e4a11120-0b39-42f7-87ce-c255f05f4943.png)

**Comment by SangwooRyu** [comment]
v2.0.0에 수정하고 lately에 반영했습니다. 확인 부탁드립니다.

**Comment by SangY00n** [comment]
정상 동작함을 확인하였습니다. close 하겠습니다.
