### ISSUE TITLE
[lately][func]참석자 더보기에서 내보내기한 참가자가 참석자통계에 여전히 남아있는 오류

### ISSUE THREAD

**Issue by dmsgk724** [vmeeting-io/vmeeting_issue#126]
[발생현상]
참석자 더보기에서 특정 참가자를 내보내도 참석자 통계를 열람해보면 아직 회의에 참가중인 상태로 뜬다.

[발생일자]
2021-08-09

[재현경로]
- 발생 환경 : android
1. 참석자 더보기
2. ...메뉴에서 내보내기 혹은 채팅을 이용한 내보내기
3. 참석자 통계를 열람하면 방장권한은 해제되지만 나간상태로 되진 않음

[스크린샷 및 동영상 첨부]
![image](https://user-images.githubusercontent.com/85989698/128667004-d1e5a93e-6304-470d-8e67-12e26e4dd816.png)

**Comment by sjhan22** [comment]
IOS web 환경에서도 동일한 이슈 발생합니다.

**Comment by sajan-dpnm** [comment]
when kicking out a participant, the leaveTime and duration field is not being updated

**Comment by sajan-dpnm** [comment]
fixed by @tu-nv, code changes pushed to v2.0.0 and reflected in lately
