### ISSUE TITLE
[lately][UI] 채팅장에 "채팅" 문구 아래 "."

### ISSUE THREAD

**Issue by boonjo** [vmeeting-io/vmeeting_issue#130]
[발생현상]
 채팅장에 "채팅" 문구 아래 "." 생김

<img width="208" alt="Screen Shot 2021-08-09 at 3 06 48 PM" src="https://user-images.githubusercontent.com/61446495/128767547-96422b96-d769-43d4-88ae-284ff7b35e9d.png">

[발생일자]
2021-08-09

[재현경로]
- 발생 환경 : macOS 모든 브라우저
1. 채팅장 열기

**Comment by jungheekang** [comment]
불필요한 부분일 경우 삭제 해주세요

<img width="253" alt="스크린샷 2021-08-10 오후 1 57 48" src="https://user-images.githubusercontent.com/87403323/128810511-a2d4af17-0328-4837-9cdd-2338aedebfc8.png">

**Comment by huijjj** [comment]
lately에 수정하였습니다. 확인부탁드립니다.

**Comment by jungheekang** [comment]
확인했습니다.
