### ISSUE TITLE
[lately][func] 채팅창에서 내보내기 이후 보내거나 받은 채팅이 보이지 않음

### ISSUE THREAD

**Issue by jangyoojin** [vmeeting-io/vmeeting_issue#133]
[발생현상]
회의 참가자 중 한 명을 [특정 사용자의 채팅 - ... 메뉴 - 내보내기]를 통해 내보내면, 내보내기 이후 유입된 모든 참가자는 자신이 보낸 채팅과 다른 사용자들로부터 받은 채팅이 모두 보이지 않습니다. 다만, 새로 유입된 참가자는 채팅을 다른 사람에게 보낼 수는 있습니다. 아래 사진을 보면 새로 유입된 참가자가 보낸 채팅이 기존 참가자에게는 보입니다.

[발생일자]
2021.08.10

[재현경로]
- 발생 환경 : 윈도우 OS 모든 웹 브라우저(크롬, 엣지, 오페라, 네이버 웨일)
1. 세 명의 참가자가 한 회의에 접속하고 각자 채팅을 하나씩 보냄
2. 방장이 한명을 내보내기 기능을 통해 회의에서 내보냄
3. 이후 새로운 참가자가 회의에 접속하여 채팅을 치면 새로운 채팅이 보이지 않음을 확인
4. 기존 참가자가 채팅을 보내도 새로운 참가자의 채팅창에서는 보이지 않음

[스크린샷 및 동영상 첨부]
![image](https://user-images.githubusercontent.com/74976893/128809151-67d3a8a2-c7a2-4d3d-8bb5-86ea17f42cde.png)
![image](https://user-images.githubusercontent.com/74976893/128809163-77534459-743a-4ee7-82c6-e2a0eca0c1bb.png)

**Comment by sajan-dpnm** [comment]
코드 수정하고 lately에서 deploy 완료 됐습니다. @jangyoojin @jungheekang 확인 부탁드립니다!

**Comment by jangyoojin** [comment]
정상 동작하는 것을 확인했습니다.
