### ISSUE TITLE
[lately][func] Meeting rooms are not destroyed when timeRemained expires.

### ISSUE THREAD

**Issue by theun0524** [vmeeting-io/vmeeting_issue#134]
[발생현상]
회의 시간이 종료되어도 회의가 종료되지 않고 계속 진행됨.

[발생일자]
2021.08.10

[재현경로]
- 발생 환경 : Chrome
1. 관리자 권한으로 로그인 함.
2. 크롬에 탭을 두개 만들고 하나는 회의를 생성해서 참여함.
3. 나머지 탭에서는 관리자 콘솔로 들어가서 진행중인 회의의 남은 시간을 변경함.
4. 남은 시간이 만료되어도 회의가 종료되지 않음.

[스크린샷 및 동영상 첨부]
ejabberd 에서 아래과 같은 에러 로그가 발생함.
2021-08-10 05:39:37.557719+00:00 [error] Error in process <0.1083.0> on node ejabberd@30813da28723 with exit value:
{undef,[{mod_site_license,destroy_room,
                          [<0.1055.0>,<<"duration_expired">>],
                          []}]}

**Comment by tu-nv** [comment]
fixed in latest v2.0.0
