### ISSUE TITLE
[lately][UI] 본인의 화면에서 추가메뉴(...) 크기 다름

### ISSUE THREAD

**Issue by jangyoojin** [vmeeting-io/vmeeting_issue#136]
[발생현상]
2명 이상의 참가자가 접속했을 때, 타일뷰 상태에서 본인의 화면 추가 메뉴(...) 크기가 작게 표시됩니다. 아래 사진 상에서 비교해보시면 알 수 있습니다.

[발생일자]
2021.08.10

[재현경로]
- 발생 환경 : window OS 모든 웹 브라우저 
1. 2인 이상 한 회의에 접속
2. 타일뷰로 전환
3. 참가자들 화면에 보이는 ... 크기 비교

[스크린샷 및 동영상 첨부]
![image](https://user-images.githubusercontent.com/74976893/128837012-d12b50f0-2bde-4e19-a6b5-9f969b4588ed.png)

**Comment by huijjj** [comment]
lately에 수정하였습니다 확인부탁드립니다

**Comment by jangyoojin** [comment]
확인했습니다
