### ISSUE TITLE
[lately][func] 채팅에서 A에게 개인메시지 활성화 상태에서 A가 회의종료시 vmeeter, follow jitster로 변경됨

### ISSUE THREAD

**Issue by jungheekang** [vmeeting-io/vmeeting_issue#138]
[발생현상]
채팅에서 A에게 개인메시지 활성화 상태에서 A가 회의종료시 vmeeter, follow jitster로 변경됨
WEB -  "A에게 개인메시지" -> "Vmeeter에게 개인메시지" 로 변경됨
app - "A에게 개인메시지" -> "Fellow Jister에게 개인메시지" 로 변경됨
- 기존이름으로 유지 필요

[발생일자]
2021-08-11

[재현경로]
- 발생 환경 : APP(21.3.0-1), web 브라우저 환경
1. 2명이상 참석 회의방
2. b 선택 - 개인메시지 보내기
3. b 회의 종료 시 a의 채팅창 확인 시 

[스크린샷 및 동영상 첨부]
- B 퇴장 전
<img width="306" alt="스크린샷 2021-08-11 오전 11 19 56" src="https://user-images.githubusercontent.com/87403323/128960345-4a999710-7f4e-4fb5-90d6-fe336a068406.png">

- B 퇴장 후
[WEB]
<img width="307" alt="스크린샷 2021-08-11 오전 11 20 15" src="https://user-images.githubusercontent.com/87403323/128960356-c541a334-5fcf-45c6-9bb0-e95754b447a4.png">

[APP]
![win_opera](https://user-images.githubusercontent.com/87403323/128960734-2aa37131-2809-412e-a983-c62c6c5758bf.png)

**Comment by sajan-dpnm** [comment]
@jungheekang 혹시 이거 어떻게 바꿔야 돼요? A 참여자가 회의종료시, 'A에게 개인메시지' 로 유지해야돼요 ?

**Comment by jungheekang** [comment]
@sajan-dpnm 개인적인 생각은 "A에게 개인메시지" 로 유지하는게 맞는것같습니다.

A가 없을때 메시지 보내면 알림 메시지가 발생되서 유지되는게 맞다고 봅니다.

**Comment by jungheekang** [comment]
@sajan-dpnm 개인메시지 대상이 퇴실하면, 지목된 개인메시지을 해제 해주세요

**Comment by sajan-dpnm** [comment]
code changes pushed to lately. 확인 부탁드립니다!

**Comment by jungheekang** [comment]
확인했습니다.
