### ISSUE TITLE
[lately][UI] 로그인 화면의 "회원가입" 문구 색상 변경 요청

### ISSUE THREAD

**Issue by jungheekang** [vmeeting-io/vmeeting_issue#140]
[발생현상]
로그인 화면의 "회원가입" 문구 색상 변경 요청
- '비밀번호 재설정' 과 동일한 색상 적용 요청

[발생일자]

[재현경로]
- 발생 환경 : APP, WEB 전체
1. 메인사이트 - 로그인
2. 로그인 페이지

[스크린샷 및 동영상 첨부]
<img width="425" alt="스크린샷 2021-08-11 오후 12 01 52" src="https://user-images.githubusercontent.com/87403323/128963316-021146bc-692d-45c2-9bdf-f5766d3aa554.png">

**Comment by huijjj** [comment]
register page에도 동일한 변경 사항 반영하겠습니다

**Comment by huijjj** [comment]
변경사항 모두 lately에 반영하였습니다
확인 부탁드립니다
