### ISSUE TITLE
[lately][func]회원가입 화면에서 캡챠 타임아웃시 00:0-1 표시 됨

### ISSUE THREAD

**Issue by jungheekang** [vmeeting-io/vmeeting_issue#141]
[발생현상]
회원가입 화면에서 캡챠 타임아웃시 00:-1 표시 됨

[발생일자]
2021-08-11

[재현경로]
- 발생 환경 : APP, WEB 
1.  회원가입 - 캡챠 시간

[스크린샷 및 동영상 첨부]

![image](https://user-images.githubusercontent.com/87403323/128967747-bed49faa-d13a-4cee-81cc-5086c8a95a83.png)

**Comment by anish9849** [comment]
Fixed. Please verify.
