### ISSUE TITLE
[lately] [enhance] 비밀번호 재설정 버튼 클릭 후 안내 문구 노출 시간 짧음

### ISSUE THREAD

**Issue by jangyoojin** [vmeeting-io/vmeeting_issue#15]
[발생현상]
계정 설정에서 비밀번호 재설정 버튼을 클릭하면 오른쪽에 '비밀번호 재설정 방법이 이메일로 전달됩니다.' 문구가 비밀번호 재설정을 위한 메일을 보냈다는 안내 문구로 변함. 그러나 이메일 인증 버튼을 눌렀을 때는 오른쪽에 안내 문구로 바뀐 후 계속 유지되지만, 비밀번호 재설정의 경우 안내 문구가 잠시 보인 후 다시 원래 문구로 돌아오는 것을 확인. 안내 문구로 계속 유지되게 수정하면 좋을 것 같음

[발생일자]
2021.07.22

[재현경로]
- 발생 환경 : 윈도우 크롬
1. 메인 화면 - 계정 설정 - 비밀번호 재설정 버튼 클릭
2. 오른쪽 문구를 관찰

[스크린샷 및 동영상 첨부]
![image](https://user-images.githubusercontent.com/74976893/126619414-cc1369e7-604c-4b7f-a889-56a366c6d1fc.png)
![image](https://user-images.githubusercontent.com/74976893/126619367-3930e6c7-56b7-4350-b0b9-ca100c9ad442.png)

**Comment by jungheekang** [comment]
모든 os, 브라우저 동일, 우선순위 낮음

**Comment by huijjj** [comment]
@jungheekang 
안녕하세요, 과장님

어떻게 수정하는 것이 좋을지 잘 모르겠어서 댓글 남깁니다.
 
버튼을 클릭하고 나오는 문구를 계속 유지하도록 수정하면 될까요?
혹은, 현재 6초로 설정되어 있는 시간을 10초나 그 이상으로 늘리는 것이 좋을까요?

**Comment by huijjj** [comment]
다른 버튼을 누르기 전까지는 문구가 유지되도록 수정하여 lately에 반영했습니다
