### ISSUE TITLE
[lately][UI] A에게 개인 메시지 발송 시 A가 퇴장하여 없을 때 발생되는 문구 변경 요청

### ISSUE THREAD

**Issue by jungheekang** [vmeeting-io/vmeeting_issue#151]
[발생현상]
A에게 개인 메시지 발송 시 A가 퇴장하여 없을 때 발생되는 문구 변경 요청

[한국어]
오류 : 메시지가 전송되지 않았습니다. 이유 : Recipient is not in the conference room
-> 메시지가 전송되지 않았습니다. <줄바꿈> 수신인이 회의실에 없습니다.

[영어]
Error: your message was not sent. Reason: Recipient is not in the conference room
-> your message was not sent. <줄바꿈> Recipient is not in the conference room

[발생일자]
2021-08-12

[재현경로]
- 발생 환경 : 전체환경
1. 여러명 회의 참석
2. 참석자 목록 - A 의 ... 선택
3. 개인메시지 보내기
4. A 회의실에서 퇴장
5. 채팅창에 채팅 입력 시 발생되는 메시지 확인

[스크린샷 및 동영상 첨부]
<img width="253" alt="스크린샷 2021-08-12 오후 4 05 55" src="https://user-images.githubusercontent.com/87403323/129153632-c37f0b3f-f30f-4a74-bd5f-15212a78dadb.png">

**Comment by sajan-dpnm** [comment]
the error message should be changed from "Error: your message was not sent. Reason: Recipient is not in the conference room" to "Your message was not sent. \n Recipient is not in the conference room" ? Apparently there is also a styling error related with flexbox and timestamp in this scenario

**Comment by jungheekang** [comment]
@sajan-dpnm So, is it possible to delete only "Error:", "Reason:" (kor : "Error :", "Reason:") from the error message?

**Comment by sajan-dpnm** [comment]
yes, it is possible!

**Comment by jungheekang** [comment]
@sajan-dpnm 적용 부탁드립니다. APP에는 적용되어 있습니다.(은실장님)

**Comment by sajan-dpnm** [comment]
okay

**Comment by sajan-dpnm** [comment]
code changes to lately!

**Comment by jungheekang** [comment]
확인하였습니다.
