### ISSUE TITLE
[lately][func] 크롬에서 화면 공유가 안되는 문제

### ISSUE THREAD

**Issue by jangyoojin** [vmeeting-io/vmeeting_issue#152]
[발생현상]
한 참가자가 화면공유를 하고 있을 때, 다른 참가자(크롬 유저)가 판서를 열었다가 닫으면 판서를 열었다가 닫은 참가자는 이후 화면공유 시 에러가 발생합니다. 화면공유를 하던 참가자가 화면공유를 중지하면 다른 참가자(크롬 유저)가 판서를 열었다가 닫지 않아도 판서가 자동으로 닫힙니다. 이렇게 판서가 닫긴 경우에도 이후 화면공유 시 에러가 발생합니다.

[발생일자]
2021.08.12

[재현경로]
- 발생 환경 : 윈도우os 크롬 브라우저
1. 2명 이상의 참가자가 한 회의에 접속(한명은 크롬을 사용해서 접속)
2. 한 참가자가 화면 공유를 하는 동안, 크롬 유저가 판서를 열고 닫음
3. 화면 공유 하던 참가자는 화면 공유를 중지하고 크롬 유저가 화면공유를 시도
4. 아래와 같은 에러가 발생하거나 오류 페이지가 뜸

[스크린샷 및 동영상 첨부]
![image](https://user-images.githubusercontent.com/74976893/129159871-dd13f844-a4ad-41ea-99bb-20a3ddc394de.png)
![image](https://user-images.githubusercontent.com/74976893/129159885-66a0044c-2af8-4573-a742-c6bfbc7bfe3a.png)

**Comment by jungheekang** [comment]
VP9의 크롬 이슈. vmeeting은 vp8으로 고정으로 변경
