### ISSUE TITLE
[lately][func] YouTube 비디오 공유 후 종료해도 화면포커스가 비디오 공유을 위해 입장된 video(fellow jister)로 되어있음

### ISSUE THREAD

**Issue by jungheekang** [vmeeting-io/vmeeting_issue#155]
[발생현상]
YouTube 공유 후 종료해도 화면포커스가 비디오 공유을 위해 입장된 video(fellow jister)로 되어있음
비디오 종료 시 방장 화면 또는 공유한 대상자화면으로 포커스가 되면 될것같습니다.
(타일뷰일때는 안보이고 전체화면일때 보여집니다.)

[발생일자]
2021-08-12

[재현경로]
- 발생 환경 : app(21.3.0-3), web 
1. 여러명 참가 회의생성
2. 방장 - youtube비디오 공유 - 비디오 공유 종료
3. 참가자 화면 확인 시 

[스크린샷 및 동영상 첨부]
- app 화면
![IMG_588695D020B3-1](https://user-images.githubusercontent.com/87403323/129165234-98dec0a6-2169-4954-8402-237b3f328420.jpeg)

- web 화면
![Aug-12-2021 17-36-52](https://user-images.githubusercontent.com/87403323/129165961-afc5d4d7-a52f-4984-ad13-c2bfed122e51.gif)

**Comment by sajan-dpnm** [comment]
@jungheekang this issue has been fixed and confirmed by @anish9849 that this issue is no longer seen in the new build. @jungheekang Please confirm
