### ISSUE TITLE
[lately][func]android app에서 회의종료 - app종료 후 다시 회의실 입장 시 본인계정이 여러개 나옴

### ISSUE THREAD

**Issue by jungheekang** [vmeeting-io/vmeeting_issue#156]
[발생현상]
android app에서 회의종료 - app종료 후 다시 회의실 입장 시 본인계정이 여러개 나옴

[발생일자]
2021-08-13

[재현경로]
- 발생 환경  android app(21.3.0-5)
1. 안드로이드 app 실행 - 기존 3인이 참석되어있는 A 회의실 참석
2. 회의나가기 - back key로 어플종료
3. 안드로이드 app 실행 - 기존 A 회의실 재진입 시 

[스크린샷 및 동영상 첨부]

https://user-images.githubusercontent.com/87403323/129299712-b1875d13-135a-4be5-aaee-67308dbf7a9d.mp4

**Comment by ktm526** [comment]
기존 회의실 재진입이 아닌, 새로 생성한 회의실 진입 시에도 본인 계정이 여러 개 나오는 현상이 발생했습니다. 

#158번 이슈를 테스트 하기 위해 다른 참가자 6~7명 가량이 접속해 있던 방에서 back key, 앱의 회의 종료 버튼을 각각 사용하여 회의에서 나온 뒤 다시 재접속을 한 이후 본인 계정이 3개로 보이는 버그가 발생하였습니다. 이후 버그가 발생한 해당 방이 아닌, 새로 생성한 방에 접속을 시도하였는데 이 때도 동일하게 본인 계정이 계속해서 3개로 보입니다.

https://user-images.githubusercontent.com/77431608/129650346-3b242e3b-c76c-4f85-98a1-6a72ded8c25a.mp4

![ezgif com-gif-maker (5)](https://user-images.githubusercontent.com/77431608/129650403-51d71b50-ebce-4d31-987a-39d4b9f7aa69.gif)

**Comment by theun0524** [comment]
@ktm526 재현 경로 좀 자세히 기술 부탁합니다.

**Comment by theun0524** [comment]
@ktm526 수정되었습니다.
Android v21.3.0 build 8287714
iOS v21.3.0 build 7
위 버전에서 수정 확인하고 close 부탁합니다.

**Comment by jungheekang** [comment]
Android v21.3.0 build 8287714
iOS v21.3.0 build 7에서 현상 재현안되는거 확인했습니다.
