### ISSUE TITLE
[lately][func]앱에서 로그인한 참석자에게는 무조건 방장 권한이 부여되는 현상

### ISSUE THREAD

**Issue by dmsgk724** [vmeeting-io/vmeeting_issue#159]
[발생현상]
이미 방에 방장이 있음에도 불구하고  로그인하고 방에 접속할 시 무조건 방장 권한이 부여됩니다.
Closed된 4번 이슈가 앱에서 적용된 현상입니다.

[발생일자]
2021-08-13

[재현경로]
- 발생 환경 : 
1. 방에 이미 기존 방장 존재
2. 로그인하여 앱에서 방에 참석
3. 방장권한이 자동으로 부여됨

[스크린샷 및 동영상 첨부]

**Comment by theun0524** [comment]
@dmsgk724 수정되었습니다.
Android v21.3.0 build 8287714
iOS v21.3.0 build 7
위 버전에서 확인 후 close 부탁 합니다.

**Comment by dmsgk724** [comment]
ios와 android모두 testing한 결과 정상적으로 작동하는 것을 확인하여 close합니다.
