### ISSUE TITLE
[lately][func]android app에서 타일뷰 모드일때 스크롤이 되지 않음

### ISSUE THREAD

**Issue by jungheekang** [vmeeting-io/vmeeting_issue#160]
[발생현상]
android app에서 타일뷰 모드일때 스크롤이 되지 않아 아래참가자을 볼수 없음
(iOS app정상적으로 스크롤됩니다.)

[발생일자]
2021-08-13

[재현경로]
- 발생 환경 : android app
1. 7명 이상 참가한 회의실
2. 타일뷰 모드 ON
3. 타일뷰가 스크롤이 되지 않음

**Comment by dmsgk724** [comment]
정상 스크롤 되는 것 확인하여 이슈 클로즈 합니다
