### ISSUE TITLE
[lately][func] 배경 선택 시에 Desktop Share를 선택하고 '오디오 공유' 체크하여 공유 및 적용을 시도 할 경우 배경이 정상적으로 적용되지 않는 현상

### ISSUE THREAD

**Issue by SangY00n** [vmeeting-io/vmeeting_issue#161]
[발생현상]
배경 선택 시에 Desktop Share를 선택하고 '오디오 공유' 체크하여 공유 및 적용을 시도 할 경우 배경이 정상적으로 적용되지 않고 회색(타일뷰 토글 off 상태) 또는 검은색(타일뷰 토글 on 상태)의 배경이 출력됩니다.

[발생일자]
2021.08.17

[재현경로]
- 발생 환경 : WindowOS의 모든 브라우저
1. 추가 액션(...) - 배경 선택
2. Desktop Share 선택 - 오디오 공유 체크 - 공유

[스크린샷 및 동영상 첨부]
![image](https://user-images.githubusercontent.com/85980653/129650450-e5726e89-9132-4bfb-a679-7ff0b6574fed.png)

**Comment by jungheekang** [comment]
@SangwooRyu 안녕하세요. 배경설정 - 화면공유 경로오는게 별도로 있다면 오디오공유 체크박스 disable 부탁드립니다.
화면공유 소스을 같이 쓰는경우는 예외처리 가능한지 검토 부탁드립니다.

**Comment by jungheekang** [comment]
@SangwooRyu 현재 lately에서 알럿메시지가 발생되지 않고 바로 적용되고 있습니다. 아래 내용이 적용이 안된것으로 보여집니다. 확인부탁드립니다.


#250번 이슈의 커멘트입니다.
배경이 공유하려는 화면으로 나오도록 수정하였고, 오디오 공유를 할 수 없도록 직접 수정할 수 없어서 오디오 공유를 체크하는 경우 일단 아래와 같이 경고 메시지가 뜨도록 수정했습니다.
jitsi-meet feat/#250_background_issue 브랜치 https://github.com/vmeeting-io/jitsi-meet/commits/feat/%23250_background_issue

**Comment by SangwooRyu** [comment]
lately에 수정되었습니다. 확인부탁드려요

**Comment by SangY00n** [comment]
확인하였습니다. 이슈 close 하겠습니다.
