### ISSUE TITLE
[lately][func] 방장이 로비모드 활성화 시 방장만 회의 시간이 초기화되는 현상

### ISSUE THREAD

**Issue by SangY00n** [vmeeting-io/vmeeting_issue#165]
[발생현상]
방장이 로비모드를 활성화 시 방장에게 표시되는 회의 시간이 초기화됩니다.
기존에 회의 참여자들은 회의 시간이 정상적으로 출력되며, 로비모드 활성화 이후 참여한 회의 참여자들은 방장과 동일하게 로비모드 활성화 이후부터의 회의 시간이 출력됩니다.

[발생일자]
2021.08.18

[재현경로]
- 발생 환경 : WindowOS의 모든 브라우저, iOS 앱 21.3.0(7)
1. 방장이 추가 액션 - 보안 옵션 - 로비 활성화
2. 회의 시간 확인

[스크린샷 및 동영상 첨부]

https://user-images.githubusercontent.com/85980653/129829193-d9459517-785f-4e1b-a779-93286bcaf4c4.mp4

**Comment by anish9849** [comment]
@SangY00n could not reproduce this issue. Could you please verify it on lately ?

**Comment by SangY00n** [comment]
I think this issue no longer occurs on lately. I will close this.
