### ISSUE TITLE
[lately][UI] 설정 - 기타 - 방장 "모두 나와같은 설정 상태로" 문구 변경 요청

### ISSUE THREAD

**Issue by jungheekang** [vmeeting-io/vmeeting_issue#169]
[발생현상]
설정 - 기타 - 방장 권한 체크박스메뉴의 "모두 나와 같은 설정 상태로 문구 변경 요청

- 모두 나와 같은 설정 상태로  ->  모두 나와 같은 화면 상태로

[발생일자]
2021-08-20

[재현경로]
- 발생 환경 : 전체
1. 회의실 생성 및 입장 (권한 : 방장) - 추가 액션 
2. 설정 - 기타 tab - 방장 메뉴

**Comment by anish9849** [comment]
Please verify!

**Comment by jungheekang** [comment]
확인했습니다.
