### ISSUE TITLE
[lately][func] Safari에서 배경설정시 카메라 오류

### ISSUE THREAD

**Issue by boonjo** [vmeeting-io/vmeeting_issue#17]
[발생현상]

배경 선택시 카메라 작동 오류

![background](https://user-images.githubusercontent.com/61446495/126727532-7eded886-91a7-4a3f-a171-5362005adaf0.gif)

[발생일자]

2021-07-23

[재현경로]
- 발생 환경 : macOS Safari
1. 메인화면
2. 로그인 계정명
3. 배경선택

**Comment by jungheekang** [comment]
safari 환경에선 배경선택 메뉴 삭제 - 주간회의 내용

**Comment by theun0524** [comment]
수정됨. lately 에서 확인하고 close 부탁합니다.

**Comment by jungheekang** [comment]
safari 브라우저에서 배경설정 메뉴 미표출 확인하였습니다.
