### ISSUE TITLE
[lately][UI]하단 toolbar 채팅아이콘 마우스 오버시 문구 변경 요청

### ISSUE THREAD

**Issue by jungheekang** [vmeeting-io/vmeeting_issue#170]
[발생현상]
하단 toolbar 채팅아이콘 마우스 오버시 문구 변경 요청
- 대화 열기 -> 채팅창 열기
- 대화 종료 -> 채팅창 닫기

[발생일자]
2021-08-20

[재현경로]
- 발생 환경 : 전체
1. 회의실 입장 - 하단 툴바의 채팅아이콘 문구

**Comment by anish9849** [comment]
Please verify.

**Comment by jungheekang** [comment]
확인했습니다.
