### ISSUE TITLE
[lately][func]로그인된 상태에서 회의 참여하여 설정 - 프로필 tab에 로그인 버튼 표출

### ISSUE THREAD

**Issue by jungheekang** [vmeeting-io/vmeeting_issue#171]
[발생현상]
로그인된 상태에서 회의 참여하여 설정 - 프로필 tab에 로그인 버튼 표출됨
(로그인된 상태면 로그아웃 버튼이 표출되어야됨)
로그인 버튼 누르면 로그인페이지 이동 후 다시 회의로 복귀되고 계속 로그인으로 표출

[발생일자]
2021-08-20

[재현경로]
- 발생 환경 : 전체
1. 기 생성되어있던 A회의
2. 로그인상태에서 A회의 참여 - 추가 액션 - 설정 
3. 프로필 tab - 하단 인증하기 영역

[스크린샷 및 동영상 첨부]
![Aug-20-2021 14-12-21](https://user-images.githubusercontent.com/87403323/130182698-d30a823b-47ae-4430-9806-470d4d2272bb.gif)

**Comment by anish9849** [comment]
Couldn't reproduce this issue on following env. @jungheekang  Could you please check it once again if this bug can be reproduced  ?

Branch: v2.0.0
Commit: 3aabbcad26bf34f0a4d915f1d3a5f8415b9af729

1. OS: Ubuntu(21.04 LTS),  Browsers: [Brave Browser, Chromium]
![Issue#](https://user-images.githubusercontent.com/85114817/130384442-52ef33f1-2631-4b27-915b-58ccf5daaf2f.gif)

2. OS: MacBook(Big Sur), Browsers: [Safari, Chrome]
![image](https://user-images.githubusercontent.com/85114817/130384470-0e90645f-8d1e-4254-88ee-a72a39f1d3e8.png)

**Comment by jungheekang** [comment]
@anish9849 If you attend an existing conference room as a "logged-in attendee," the reality will be reproduced. (moderator X)

**Comment by anish9849** [comment]
Ah.. Got the issue. Thank you for the clarification. I will look into it.

**Comment by anish9849** [comment]
@jungheekang Please verify it.

**Comment by jungheekang** [comment]
확인했습니다.
