### ISSUE TITLE
[lately][func]로그인상태에서 메인화면의 설정 - 프로필 tab의 이름, 이메일 항목 수정불가 처리 필요

### ISSUE THREAD

**Issue by jungheekang** [vmeeting-io/vmeeting_issue#172]
[발생현상]
로그인상태에서 메인화면의 설정 - 프로필 tab의 이름, 이메일 항목 수정불가 처리 필요

로그인상태에서는 메인화면의 설정 - 프로필tab에서 변경해도 회의에 참석하면 반영되지않고 초기화되어 입력불가 처리 필요

(회의실에서의 추가액션 - 설정 - 프로필tab에서 변경은 회의실에서 보여지는이름이 바뀌므로 유지필요
(계정 정보는 변경되지 않아도 회의실의 이름은 변경 가능함))

[발생일자]
2021-08-20

[재현경로]
- 발생 환경 : web 전체
1. 로그인 상태
2. 메인화면 - 설정 - 프로필 tab 
3. 이름설정, 이메일설정 항목 변경
4. 회의실 입장 시 변경한 내용으로 표시되지 않고, 기존 계정정보가 표시

[스크린샷 및 동영상 첨부]

**Comment by anish9849** [comment]
@jungheekang  Please verify at lately.

**Comment by jungheekang** [comment]
확인했습니다.!!!
