### ISSUE TITLE
[lately][UI] 하단 toolbar 메뉴명은 '참가자 목록', 활성화된 창에는 '참석자 목록'으로 표기가 다름

### ISSUE THREAD

**Issue by jungheekang** [vmeeting-io/vmeeting_issue#174]
[발생현상]
하단 toolbar 메뉴명은 '참가자 목록', 활성화된 창에는 '참석자 목록'으로 표기됨 
참가자 -> 참석자 변경 필요(참석자로 모두 통일 필요)

[참고자료. 네이버국어사전]
참석 : 모임이나 회의 따위의 자리에 참여함.
참가 : 모임이나 단체 또는 일에 관계하여 들어감.

[발생일자]
2021-08-20

[재현경로]
- 발생 환경 : web, app 전체
1. 하단 toolbar 의 '참가자 목록' 선택
2. 측면 '참가자목록' 창 문구 확인 시

[스크린샷 및 동영상 첨부]
- APP
![image](https://user-images.githubusercontent.com/87403323/130187012-0c995b0e-6cae-4577-9784-538d2b7839d5.png)

- WEB
<img width="77" alt="스크린샷 2021-08-20 오후 2 53 23" src="https://user-images.githubusercontent.com/87403323/130187041-d2debf15-f36b-4250-8bbf-69c42287b18f.png">

**Comment by anish9849** [comment]
@jungheekang I am little confused with the description of the text, sorry for having poor korean :(. 

Are we supposed to change all "참가자"  to "참석자" ?

**Comment by jungheekang** [comment]
@anish9849 "참석자" 입니다.

**Comment by anish9849** [comment]
@jungheekang  Please verify this on new release 21.3.1.

**Comment by jungheekang** [comment]
@anish9849  "참석자" 수정해달라고 요청했는데 모두(web,app) "참가자"로 수정되어 있습니다.
