### ISSUE TITLE
[lately][UI]로비모드 활성화 상태, 참석자목록에서 수락/거부 버튼 위치 변경 요청

### ISSUE THREAD

**Issue by jungheekang** [vmeeting-io/vmeeting_issue#175]
[발생현상]
로비모드 활성화 상태, 참석자목록에서 회의참석 요청자 수락/거부 버튼 위치 변경 요청
 - 수락,  거부  순서로 변경 필요

[발생일자]
2021-08-20

[재현경로]
- 발생 환경 : web
1. 로비모드 활성화
2. 참여자 회의 참석 요청
3. 참석자 목록 의 참여자요청 목록 확인 시

[스크린샷 및 동영상 첨부]
- 회의 화면에서의 수락/거부 버튼
<img width="221" alt="스크린샷 2021-08-20 오후 6 51 18" src="https://user-images.githubusercontent.com/87403323/130215857-0b2ae799-5650-4a2f-9e5b-fee53d0a5f0b.png">

- 참석자목록에서의 수락/거부 버튼
<img width="307" alt="스크린샷 2021-08-20 오후 6 50 58" src="https://user-images.githubusercontent.com/87403323/130216046-64dcee7c-bfa8-49c6-a00c-f012975046aa.png">

**Comment by anish9849** [comment]
Please verify at https://github.com/vmeeting-io/jitsi-meet/commit/90f25e12cfab782ed4b9d938d4a3b41c28f5aa6e

**Comment by jungheekang** [comment]
확인했습니다.
