### ISSUE TITLE
[lately][UI]회원가입 화면에서 프로필 이미지 설정 영역에 문구 추가 필요

### ISSUE THREAD

**Issue by jungheekang** [vmeeting-io/vmeeting_issue#176]
[발생현상]
회원가입 화면에서 프로필 이미지 설정 영역에 문구 추가 필요
"*프로필 이미지" 추가

[발생일자]
2021-08-23

[재현경로]
- 발생 환경 : 전체
1. 메인화면 - 회원가입 - 회원가입 화면

[스크린샷 및 동영상 첨부]
<img width="167" alt="스크린샷 2021-08-23 오후 2 31 33" src="https://user-images.githubusercontent.com/87403323/130395568-c6520b39-f500-4084-91bb-f92f536da376.png">

**Comment by sajan-dpnm** [comment]
code changes pushed to lately!

**Comment by jungheekang** [comment]
확인했습니다.
