### ISSUE TITLE
[flagship][func] 개인메시지 보내기 중첩 시 수신자 이름이 바뀌지 않는 현상

### ISSUE THREAD

**Issue by SangY00n** [vmeeting-io/vmeeting_issue#178]
[발생현상]
_참여자1_ 에게 개인메시지 보내기를 시도 중 _참여자2_ 에게 개인메시지 보내기를 시도하면
메시지 입력 창 위에 ' _참여자1_ 에게 개인메시지' 와 같이 수신자 이름이 바뀌지 않고 그대로 유지됩니다.

전송 버튼을 누르면 개인메시지는 참여자2에게 제대로 전송됩니다.

[발생일자]
2021.08.24

[재현경로]
- 발생 환경 : WindowOS의 모든 브라우저
1. 참여자1에게 개인메시지 보내기 클릭
- 참여자1의 개인메시지에 회신하기 또는
- 참여자1 더보기(...) - 개인메시지 보내기 또는
- 참가자 목록 - 참여자1 더보기(...) 개인메시지 보내기
2. 참여자2에게 개인메시지 보내기 클릭
- 참여자2의 개인메시지에 회신하기 또는
- 참여자2 더보기(...) - 개인메시지 보내기 또는
- 참가자 목록 - 참여자2 더보기(...) 개인메시지 보내기
3. 메시지 입력 창 위의 수신자 이름 확인

[스크린샷 및 동영상 첨부]

https://user-images.githubusercontent.com/85980653/130562048-dcc6d856-6d6f-4561-9de9-659405235e21.mp4

**Comment by sajan-dpnm** [comment]
code changes were pushed to lately and seems to be working fine in lately. the issue in flagship will be removed once the latest build is used in flagship

**Comment by SangY00n** [comment]
lately에서 확인하였습니다! 이슈 close 하겠습니다.
