### ISSUE TITLE
[lately][func] 대화창이 꺼져 있을 때 개인메시지 보내기 시도 시 수신자 이름이 표시되지 않는 현상

### ISSUE THREAD

**Issue by SangY00n** [vmeeting-io/vmeeting_issue#179]
[발생현상]
대화창이 꺼져 있을 때 회의 참여자 중 한 명에게 개인메시지 보내기를 시도하였을 때,
메시지 입력창 위에 '에게 개인메시지'와 같이 수신인의 이름이 표시되지 않습니다.

[발생일자]
2021.08.24

[재현경로]
- 발생 환경 : WindowOS의 모든 브라우저
1. (대화창이 열려 있다면) '대화 종료'를 눌러 대화창 닫기
2. 개인메시지 보내기 클릭
- 참가자 더보기(...) - 개인메시지 보내기 또는
- 참가자 목록 - 더보기(...) - 개인메시지 보내기
3. 메시지 입력창 확인

[스크린샷 및 동영상 첨부]
![image](https://user-images.githubusercontent.com/85980653/130562916-1cf217ce-bd26-4975-bcdb-2f3786728cae.png)

**Comment by sajan-dpnm** [comment]
@SangY00n related with issue 138, solving that issue will solve this issue!

**Comment by sajan-dpnm** [comment]
upload gif please!

**Comment by SangY00n** [comment]
![Animation_2021-08-24-15-18-57](https://user-images.githubusercontent.com/85980653/130566194-e30a5732-7ea7-44de-aafc-a90bccbc3d4c.gif)

The text above the message field is '에게 개인메시지', not ' _참가자1_ 에게 개인메시지'.
It must to be ' _참가자1_ 에게 개인메시지'.

**Comment by sajan-dpnm** [comment]
reverted the code changes and pushed to lately!

**Comment by sajan-dpnm** [comment]
@SangY00n please confirm if it is working now!

**Comment by SangY00n** [comment]
확인하였습니다. 이슈 close 하겠습니다.
