### ISSUE TITLE
[lately][func] 아이폰 메인화면에서의 배경선택 옵션 제공

### ISSUE THREAD

**Issue by sjhan22** [vmeeting-io/vmeeting_issue#18]
[발생현상]
모바일에서는 배경 선택 기능을 제공하지 않는데, 아이폰 chrome web으로 접속 시 메인화면에서 배경선택 옵션이 제공됨.
배경 적용시 배경이 제대로 적용되지 않고 검정색 화면이 뜸.

[발생일자]
2021.07.22

[재현경로]
- 발생 환경 : 아이폰 모든 브라우저 web
1. 메인화면 - 로그인계정명 - 배경선택 - 원하는 배경선택- 적용
2. 
3.

[스크린샷 또는 동영상]
![image](https://user-images.githubusercontent.com/85981002/126593432-3beb37e5-6de4-4945-a3c6-52d55da266cf.png)

**Comment by theun0524** [comment]
수정됨. lately 에서 확인하고 close 부탁합니다.
