### ISSUE TITLE
[lately] 회원가입 버튼 클릭 시 loading 문구 변경 요청

### ISSUE THREAD

**Issue by SangY00n** [vmeeting-io/vmeeting_issue#181]
[발생현상]
회원가입 시 회원 정보 입력 후 회원가입 버튼을 눌렀을 때, 버튼에 'loading회원가입' 이라는 문구가 출력됩니다.
해당 문구를 'loading' 또는 '로드 중'과 같이 변경하는 것이 좋을 것 같습니다.

[발생일자]
2021.08.27

[재현경로]
- 발생 환경 : WindowOS의 모든 웹브라우저
1. 메인 홈페이지에서 회원가입
2. 모든 회원정보 기입 후 회원가입 버튼 클릭
3. 'loading회원가입' 문구 출력

[스크린샷 및 동영상 첨부]
![image](https://user-images.githubusercontent.com/85980653/131082193-f8af00bb-87d5-4307-a03b-93f4b70b7281.png)

언어가 한국어일 때
![image](https://user-images.githubusercontent.com/85980653/131081621-5018aa32-8002-4ea3-aa58-c81f7f2a928e.png)

언어가 영어일 때
![image](https://user-images.githubusercontent.com/85980653/131081839-efa9909c-661a-4748-8f30-03922fa88dbd.png)

**Comment by anish9849** [comment]
@jungheekang Fixed at lately, Please verify it.

**Comment by SangY00n** [comment]
수정 확인하였습니다. 이슈 close 하겠습니다.
