### ISSUE TITLE
[flagship][func] 로비모드 활성화-비활성화 시 나타나는 접속자 통계 오류

### ISSUE THREAD

**Issue by SangY00n** [vmeeting-io/vmeeting_issue#182]
[발생현상]
방장 권한을 가진 참가자 중 한 명이 로비모드를 활성화했다가 비활성화할 경우, 접속자 통계에서 방장 권한을 가진 참가자들의 종료 시간과 접속 시간이 기록되며, 이름이 회색으로 출력됩니다.

[발생일자]
2021.08.27

[재현경로]
- 발생 환경 : WindowOS의 모든 웹브라우저
1. 방장 권한을 가진 참가자 중 한 명이 추가 액션(...) - 보안 옵션 에서 로비 활성화했다가 다시 비활성화로 전환
2. 추가 액션(...) - 접속자 통계 확인

[스크린샷 및 동영상 첨부]

https://user-images.githubusercontent.com/85980653/131091476-25c5e189-a75b-4a8a-a2f6-cc71a87d4a50.mp4

**Comment by theun0524** [comment]
수정완료. lately에서 확인 부탁합니다.
