### ISSUE TITLE
[lately][UI]메인사이트 화면의  매뉴얼 메뉴 기능 변경

### ISSUE THREAD

**Issue by jungheekang** [vmeeting-io/vmeeting_issue#187]
[발생현상]
메인화면 메뉴 기능 변경
 - 첨부된 사진 참고
  1. Features (/auth/page/features) 화면 -> Features 드롭다운 방식
  2. 설정된 언어에 맞게 다운로드, 매뉴얼 google site 연결 설정
      (한국어설정 시 한국어 매뉴얼 다운로드, 구글 매뉴얼 사이트 연결
       영어 (기타 모든 언어) 언어 설정 시 영어 매뉴얼 다운로드, 구글 매뉴얼 사이트 연결)
  3. Supports는 기존 contact us와 동일하게 동작 supports 누르면 이메일로 연결

- 메뉴얼과 연결 URL은 준비되는대로 전달예정이며, 
  기능을 구현해놓고 파일은연결은 더미로 해놓고 문서 전달되면 파일수정하는방식으로 진행

[발생현상]
Main screen menu function change
  - Please refer to the attached photo:
   1. Features (/auth/page/features) -> applied Features drop-down method
   2. Download now leads to User Guide of according language. Linked google site manual
       (Downloads Korean manual when language is set as Korean & links to Korean Google site manual &
        Downloads English manual when language is set to any other languages & links to English Google manual site)

- The Google site URL & manual will be shared after completion. For now, continue on with the implementation (Current file connected to dummy. Will be edited afterwards)

deadline : 2021-09-13 ~ 14일

[재현경로]
1. lately.vmeeting.kr의 main page

[스크린샷 및 동영상 첨부]
<img width="548" alt="image" src="https://user-images.githubusercontent.com/87403323/132786764-997cf64a-1d2a-42c0-8892-4cce4452b544.png">

**Comment by anish9849** [comment]
@jungheekang  Please verify.

**Comment by jungheekang** [comment]
@anish9849 learn more 선택 시 현재윈도우에서 열리지 않고, 새로운 탭 또는 새로운 윈도우에서 메뉴얼이 열리도록 해주세요

**Comment by jungheekang** [comment]
@anish9849 그리고 다운로드는 링크연결이 아니고, 파일 다운로드입니다.

**Comment by jungheekang** [comment]
@anish9849 만약에 가능하다면 APP의 더보기 - 도움말도 google site 메뉴얼이 연동될수있게 조치 부탁드립니다.
![image](https://user-images.githubusercontent.com/87403323/133217329-3c3a7bb6-875f-4076-9453-452a9f071f21.png)

**Comment by anish9849** [comment]
> @anish9849 언어 설정별로 메뉴언어 변경되게 해주세요

This seems to be working.

**Comment by anish9849** [comment]
> @anish9849 만약에 가능하다면 APP의 더보기 - 도움말도 google site 메뉴얼이 연동될수있게 조치 부탁드립니다.
> ![image](https://user-images.githubusercontent.com/87403323/133217329-3c3a7bb6-875f-4076-9453-452a9f071f21.png)

Ok. I will add that in the Mobile APP too.

**Comment by anish9849** [comment]
> @anish9849 그리고 다운로드는 링크연결이 아니고, 파일 다운로드입니다.

@jungheekang The link has been modified to a pdf link. Please verify.

**Comment by jungheekang** [comment]
@anish9849 app - 도움말 누르면 매뉴얼 site 연결될수있게 조치 부탁드립니다.

**Comment by jungheekang** [comment]
확인했습니다. good!!
