### ISSUE TITLE
[lately][UI] 언어:영어, "disable everyone's camera" 버튼 문구 통일 요청

### ISSUE THREAD

**Issue by jungheekang** [vmeeting-io/vmeeting_issue#189]
[발생현상]
"disable everyone's camera" 버튼 문구 2곳 통일 요청

1. 타일뷰 - 참가자 설정(...) 
   mute video everyone else -> disable video everyone else

<img width="267" alt="스크린샷 2021-09-10 오후 5 50 34" src="https://user-images.githubusercontent.com/87403323/132828702-64b8dd87-75ed-4d84-a6a8-867671f32dcc.png">

2. 참가자 목록 - 추가액션
   stop everyone's video -> disable everyone's video 

<img width="310" alt="스크린샷 2021-09-10 오후 5 56 07" src="https://user-images.githubusercontent.com/87403323/132828615-6b2fac0d-10c6-46a9-8c5e-b76855181dd7.png">

[발생일자]
2021-09-10

**Comment by sajan-dpnm** [comment]
@jungheekang I think `Mute Video Everyone Else` is the 적당한 expression in English rather than `Disable Video Everyone Else`. So I suggest we keep it as `Mute Video Everyone Else`. In the case of participant's pane, I will change to `Stop Video` -> `Mute Video` and `Stop Video Everyone Else` -> `Mute Video Everyone Else`. Please let me know if you disagree!

**Comment by jungheekang** [comment]
@sajan-dpnm Please proceed with the requested state.
1. mute video everyone else -> disable video everyone else
2. stop everyone's video -> disable everyone's video

**Comment by sajan-dpnm** [comment]
ok

**Comment by sajan-dpnm** [comment]
@jungheekang please confirm!

**Comment by jungheekang** [comment]
@sajan-dpnm
<img width="320" alt="스크린샷 2021-09-27 오후 3 02 02" src="https://user-images.githubusercontent.com/87403323/134852821-f14f803e-8140-4033-aaad-34d730f26f55.png">

**Comment by jungheekang** [comment]
@sajan-dpnm Please change word "mute video -> disable video"

**Comment by jungheekang** [comment]
@sajan-dpnm  Please change the comment text above.

**Comment by sajan-dpnm** [comment]
I pushed some code changes and it currently shows the text as below:

![image](https://user-images.githubusercontent.com/72065079/136330386-27889b23-5dc5-49de-b48a-dc6156490478.png)

![image](https://user-images.githubusercontent.com/72065079/136330481-1fbe20e7-8952-4498-819c-99c8e1a5c059.png)

**Please confirm if it is the same for you**

**Comment by jungheekang** [comment]
@sajan-dpnm 확인했습니다. 감사합니다.
