### ISSUE TITLE
[lately][UI] 언어 : eng, settings - profile 의  "gravatar" 불필요단어 삭제 요청

### ISSUE THREAD

**Issue by jungheekang** [vmeeting-io/vmeeting_issue#190]
[발생현상]
언어 : eng, settings - profile 의 "gravatar" 불필요단어 삭제 요청

set your gravatar email -> set your email

[발생일자]
2021-09-10

[재현경로]
1. 메인화면 - 셋팅 - 프로필

1. 회의실 - 추가액션 - 셋팅 - 프로필

[스크린샷 및 동영상 첨부]
<img width="584" alt="스크린샷 2021-09-10 오후 6 00 48" src="https://user-images.githubusercontent.com/87403323/132831032-3d9aa466-33b9-4be7-8b57-168402a1a012.png">

**Comment by sajan-dpnm** [comment]
code changes pushed to lately

**Comment by jungheekang** [comment]
확인했습니다.
