### ISSUE TITLE
[lately][UI] 내보내기(kick out) 아이콘, 영어 문구 통일 요청

### ISSUE THREAD

**Issue by jungheekang** [vmeeting-io/vmeeting_issue#191]
[발생현상]
내보내기(kick out) 아이콘, 영어 문구 통일 요청

1. chat ON - 발신자의 설정(...)
  - Kick-out user ->  Kick out 
  - Disable Chat for user -> Disable Chat

<img width="254" alt="스크린샷 2021-09-10 오후 6 28 40" src="https://user-images.githubusercontent.com/87403323/132833024-f686507c-0683-4b68-9e45-ab2af4d8b10d.png">

2. 타일뷰 - 참가자의 설정(...)
 
  -  ![image](https://user-images.githubusercontent.com/87403323/132833519-109710f4-7425-4b4e-986c-25717da29dd9.png)해당 아이콘으로  변경 
<img width="258" alt="스크린샷 2021-09-10 오후 6 31 40" src="https://user-images.githubusercontent.com/87403323/132833457-af470d34-9523-4cfe-bfbe-f7190e8caf25.png">

->

<img width="258" alt="스크린샷 2021-09-10 오후 6 32 58" src="https://user-images.githubusercontent.com/87403323/132833544-bb583a88-ecda-42e4-bdc0-05c6e3d339fe.png">

[발생일자]
2021-09-10

**Comment by sajan-dpnm** [comment]
pushed to v2.0.0

**Comment by jungheekang** [comment]
확인했습니다.
