### ISSUE TITLE
[flagship, lately][func] 타일뷰에서 화자 영상으로 변경되는 모드  disable 요청

### ISSUE THREAD

**Issue by jungheekang** [vmeeting-io/vmeeting_issue#192]
[발생현상]
타일뷰에서 화자 영상이 상위로 변경되는 모드 disable 요청

[발생일자]
2021-09-23

[재현경로]
- 발생 환경 : 
1. 타일뷰 - 타 참가자가 말할시 상위로 올라옴

**Comment by theun0524** [comment]
수정 완료 : lately에서 확인 부탁합니다.

**Comment by jungheekang** [comment]
확인하였습니다.
