### ISSUE TITLE
[lately][func]참석자 목록 창에 리스트 스크롤 생성되지 않음

### ISSUE THREAD

**Issue by jungheekang** [vmeeting-io/vmeeting_issue#193]
[발생현상]
참석자 목록 창에 리스트 스크롤 생성되지 않음
(소회의실 기능 추가 이후 발생됨)
[발생일자]
2021-09-23

[재현경로]
- 발생 환경 : 
1. 참석자 목록 - 참석자가 많은 경우 생성 되지 않음
1. 참석자 목록 - 소회의실이 많이 생성된 경우 스크롤 생성 되지 않음

**Comment by theun0524** [comment]
수정완료: lately에서 확인 부탁합니다.

**Comment by jungheekang** [comment]
확인했습니다.
