### ISSUE TITLE
[lately][func]Screens shared with codec VP9 are not displayed on other participants' screens

### ISSUE THREAD

**Issue by jungheekang** [vmeeting-io/vmeeting_issue#195]
[발생현상]
Screens shared with codec VP9 are not displayed on other participants' screens

[발생일자]
2021-09-23

[재현경로]
- Occurrence environment :  chrome v93.xxxx, Lately.vmeeting.kr
  
1. “A” participant screen sharing
2. The shared screen is not visible on the "B" participant's chrome screen, only a gray screen is displayed.

**Comment by tu-nv** [comment]
Yep I am working on it, but to be clear, it also happen on VP8 (I tested it). So it is not depend on codec

**Comment by tu-nv** [comment]
@jungheekang can you test the fix in flagship.vmeeting.kr? (not lately, only flagship.vmeeting.kr). I have tested 20 times with emulated packet loss, the error did not happen anymore

**Comment by jungheekang** [comment]
@tu-nv It's outside now, so I'll check it out on the flagship server later

**Comment by jungheekang** [comment]
해당 이슈 해결완료.
(크롬브라우저, VP8 아님)

[재현경로]
1. 회의생성 - 회의 녹화
2. 화면공유 - A, B, C 참가자 참석
3. 비디오 ON 시 참가자 화면에 공유화면 미표출.
