### ISSUE TITLE
[lately][recording] Participant position rendered in wrong place

### ISSUE THREAD

**Issue by tu-nv** [vmeeting-io/vmeeting_issue#196]
[발생현상]
Always happen

[발생일자]

[재현경로]
- 발생 환경 : 
1. Open a meeting with three participants in lately. E.g., https://lately.vmeeting.kr/trial/test0
2. Open another tab, copy and paste this link bellow to join: https://lately.vmeeting.kr/trial/test0#config.iAmRecorder=true&config.externalConnectUrl=null&config.startWithAudioMuted=true&config.startWithVideoMuted=true&interfaceConfig.APP_NAME="Jibri"&config.analytics.disabled=true&config.p2p.enabled=false&config.prejoinPageEnabled=false&config.requireDisplayName=false
Note that if you do not use "test0" for the meeting name, please change it in the link too
Edit: the link can actually be shorten to https://lately.vmeeting.kr/trial/test0#config.iAmRecorder=true
3. Change to tileView mode in the opened tab. The rendered position is wrong.
4. 
![image](https://user-images.githubusercontent.com/12107448/134802112-645a5397-758e-4e89-96c4-600606b85277.png)

[Note]
This error happen in when we do recording, the above link are the link jibri used to join the meeting. However, when I debug, I found that it also happen when we use real chrome browser and url params are used. Therefore, I think the issue is in frontend code. I tried to dig in but cannot find where issue it, I need your help @theun0524 @sajan-dpnm

**Comment by theun0524** [comment]
수정완료. lately에서 확인 부탁합니다.
