### ISSUE TITLE
[flagship][func] 리액션이모티콘 Silence, birthday 동작시 APP에서 화면이 흑화현상 발생

### ISSUE THREAD

**Issue by jungheekang** [vmeeting-io/vmeeting_issue#197]
[발생현상]
리액션이모티콘 Silence, birthday 동작시 APP에서 화면이 흑화현상 발생

[발생일자]
2021-09-27

[재현경로]
- 발생 환경 : APP (21.2.0 build11)(flagship)
1. web, app 접속
2. web에서 말하기버튼의 리앤션 이모티콘 Silence, birthday 선택
3. app 흑화현상 발생

**Comment by anish9849** [comment]
@jungheekang The issue has been fixed on release 21.3.1. Please check the release on testflight for ios and for andorid apk file, please check the slack room. Thanks.

**Comment by jungheekang** [comment]
@anish9849 The Android version doesn't seem to have been fixed yet. please check.
ios issue has been fixed.

**Comment by anish9849** [comment]
What is the build no of the andorid app ?

**Comment by jungheekang** [comment]
21.3.1 build 8728630

**Comment by jungheekang** [comment]
확인했습니다.
