### ISSUE TITLE
[lately][UI] 계정설정에서 버튼 로딩 동작 오류

### ISSUE THREAD

**Issue by boonjo** [vmeeting-io/vmeeting_issue#2]
[발생현상]

계정설정에서 어느 버튼을 누룰시, 모든 버튼에서 로딩 모션 동작

![button](https://user-images.githubusercontent.com/61446495/126607736-9ac26c37-d9aa-45e5-a4c8-873d78627a45.gif)

[발생일자]
2021 - 07 - 22

[재현경로]
- 발생 환경 : macOS  모든환경
1. 메인화면
2. 로그인 계정명
3. 계정설정
4. 인증 메일 보내기

**Comment by huijjj** [comment]
탈퇴를 제외한 버튼들은 각각 로딩이 따로 동작하도록 수정하여 lately에 반영했습니다
탈퇴 버튼의 경우에는 탈퇴를 누르고 굳이 다른 버튼을 누를 일이 없으며, 탈퇴 처리 중에 이메일 인증이나 비밀번호 변경시 문제가 생길 수도 있을 것 같아서 탈퇴 처리 중에는 모든 버튼이 로딩이 되도록 유지했습니다
