### ISSUE TITLE
[lately][func] 참가자목록의 참가자 추가메뉴가 브라우져 사이즈 줄이면 표출되지 않음

### ISSUE THREAD

**Issue by jungheekang** [vmeeting-io/vmeeting_issue#201]
[발생현상]
참가자목록의 참가자 추가메뉴가 브라우져 사이즈 줄이면 표출되지 않음

브라우저를 작게 줄여도 참가자 목록창은 작아지지 않는데 메뉴가 표출되지 않음
 
[발생일자]
2021-01-06

[재현경로]
1. 참가자 3명이상
2. 참가자목록 ON - 브라우저 축소 - 참가자목록의 다른참가자이름 마우스오버 시

[스크린샷 및 동영상 첨부]

<img width="612" alt="스크린샷 2021-10-06 오후 3 59 11" src="https://user-images.githubusercontent.com/87403323/136155046-31f485ca-5826-4e40-b30e-b72bc2700435.png">

**Comment by theun0524** [comment]
화면이 512보다 작아지면 참가자 컨텍스트 메뉴를 표시하지 않도록 하는 것이 디자인 컨셉입니다.
즉, 데스트탑에서는 동작시키고 패드나 모바일에서는 동작되지 않도록 설계되어 있습니다.
