### ISSUE TITLE
[lately][func]투표기능에서 항목추가 후 입력하지 않을 시 발생되는 알럿의 영어문구 없음

### ISSUE THREAD

**Issue by jungheekang** [vmeeting-io/vmeeting_issue#203]
[발생현상]
투표기능에서 항목추가 후 입력하지 않고 완료 버튼 선택시 발생되는 알럿에 영어문구 없음

[발생일자]
2021-10-06

[재현경로]
0. 브이미팅 설정 언어 : 영어
1. 투표생성 - 제목입력
2. 2개의 항목 입력 후 항목추가
3. 완료시 발생되는 알럿 문구

[스크린샷 및 동영상 첨부
![스크린샷 2021-10-06 오후 4 06 59](https://user-images.githubusercontent.com/87403323/136155996-64145cf8-8071-4751-b63c-0865aeab3e55.png)
]

**Comment by theun0524** [comment]
이 문구는 브라우저가 표시하는 문구입니다.
즉, 브라우저 언어(크롬) 또는 OS 언어(Safai) 설정에 따라 표시됩니다.
