### ISSUE TITLE
[lately][UI] 생일모자AR 메뉴 삭제 요청

### ISSUE THREAD

**Issue by jungheekang** [vmeeting-io/vmeeting_issue#204]
[발생현상]
생일모자AR 메뉴 삭제 요청
flagship, lately서버

[발생일자]
2021-10-06

[재현경로]
- 발생 환경 : 
1. 추가액션 - 생일모자AR 메뉴 삭제

[스크린샷 및 동영상 첨부]
<img width="269" alt="스크린샷 2021-10-06 오후 4 22 10" src="https://user-images.githubusercontent.com/87403323/136158506-950b02cf-964b-4ebb-8eb3-759632499632.png">

**Comment by sajan-dpnm** [comment]
@jungheekang Removed the option, please confirm

![image](https://user-images.githubusercontent.com/72065079/136330747-76c35dda-ce95-4241-ac83-3d0812f4a24d.png)
