### ISSUE TITLE
[lately][UI]리액션 기능의 조용, 축하 문구 변경 필요

### ISSUE THREAD

**Issue by jungheekang** [vmeeting-io/vmeeting_issue#205]
[발생현상]
리액션 기능의 이모티콘의 표시 이름 변경 필요

[한국어]
- silence -> 조용 
- toolbar.birthday -> 축하

[영어]
- toolbar.birthday -> Congrats

[발생일자]
2021-10-06

[재현경로]
1. 리액션 토글 - 리액션 아이콘에 마우스 오버시 표시되는 문구

[스크린샷 및 동영상 첨부]
![스크린샷 2021-10-06 오후 4 52 32](https://user-images.githubusercontent.com/87403323/136162974-b7298301-c4f3-446b-936a-111850904d89.png)

**Comment by anish9849** [comment]
@jungheekang Please verify!

**Comment by jungheekang** [comment]
확인했습니다.
