### ISSUE TITLE
[lately][func]타이머 디폴트 시간이 9sec로 되어 있음. 00로 변경 필요

### ISSUE THREAD

**Issue by jungheekang** [vmeeting-io/vmeeting_issue#206]
[발생현상]
타이머 디폴트 시간이 9sec로 되어 있음. 00로 변경 필요

- 디폴트
00 min   00 sec

[발생일자]
2021-10-07

[재현경로]
- 발생 환경 : 
1. 참가자목록 - 더보기 - 타이머

[스크린샷 및 동영상 첨부]

<img width="240" alt="스크린샷 2021-10-07 오후 4 43 21" src="https://user-images.githubusercontent.com/87403323/136341303-4ec50322-72fc-4eb4-a07c-02cd8f10407e.png">

**Comment by sajan-dpnm** [comment]
@jungheekang code changes pushed to lately. please confirm

**Comment by jungheekang** [comment]
확인했습니다.
