### ISSUE TITLE
[lately][func]타이머 59분 59초 초과될때 알럿표시 변경

### ISSUE THREAD

**Issue by jungheekang** [vmeeting-io/vmeeting_issue#207]
[발생현상]
타이머 59분 59초 초과될때 알럿표시 변경
59분 59초 초과될때 숫자인풋박스에 알럿 아이콘발생 -> 아이콘 삭제, 59분 이상 입력하면 59로 변경
클릭으로 숫자 변경시에도 59이상은 들어가지 않게 변경

[발생일자]
2021-10-07

[재현경로]
- 발생 환경 : 
1. 참가자목록 - 더보기 - 타이머
2. min 인풋박스에 60넘게 입력, sec 인풋박스에 60넘어가게 입력 시

[스크린샷 및 동영상 첨부]
<img width="245" alt="스크린샷 2021-10-07 오후 4 49 59" src="https://user-images.githubusercontent.com/87403323/136342340-3eccd186-8add-4951-9b9d-1eee2e4a3968.png">

**Comment by sajan-dpnm** [comment]
@jungheekang code changes pushed to lately, please confirm

**Comment by jungheekang** [comment]
@sajan-dpnm 확인했습니다.
