### ISSUE TITLE
[lately, flagship][func] 참가자목록 - 모두 음소거, 모두 비디오 끄기 팝업의"allow attendees to unmute themselves"기능 삭제 필요

### ISSUE THREAD

**Issue by jungheekang** [vmeeting-io/vmeeting_issue#209]
[발생현상]
참가자목록 - 모두 음소거 팝업의"allow attendees to unmute themselves"기능 삭제 필요
참가자목록 - 모두 비디오끄기 팝업의"allow attendees to start their video"기능 삭제 필요
- 해당 기능 동작되지 않음
- OFF했을때 문구가 영어로 바뀜

[발생일자]
2021-10-08

[재현경로]
- 발생 환경 : 
1. 참가자 목록
2. 모두 음소거 - 음소거 팝업의 "allow attendees to unmute themselves" 기능 ON/OFF

1. 참가자 목록 - 더보기
2. 모두 비디오 끄기 -  팝업의 "allow attendees to start their video" 기능 ON/OFF

[스크린샷 및 동영상 첨부]
https://user-images.githubusercontent.com/87403323/136485069-58144e12-ae16-471f-9744-cfdb493a1bc1.mp4

**Comment by theun0524** [comment]
수정완료) lately에 적용했습니다.
