### ISSUE TITLE
[lately][func] 아이폰에서의 사용자 차단 기능

### ISSUE THREAD

**Issue by sjhan22** [vmeeting-io/vmeeting_issue#21]
[발생현상]
사용자 차단 기능은 내보내기 기능과 동일한 작업인데 이름이 달라 사용자에게 혼란을 줄 수 있음.(용어 통일 필요)

[발생일자]
2021.07.23

[재현경로]
- 발생 환경 : 아이폰 모든 브라우저 web
1. 채팅창 열기 - 참여자 더보기 - 사용자 차단 - 차단
2.
3. 

[스크린샷 및 동영상 첨부]
![image](https://user-images.githubusercontent.com/85981002/126729068-b6ca3dbd-b24d-4179-a161-c6a19ba4971a.png)

**Comment by sajan-dpnm** [comment]
채팅창 -> 참여자 더보기 -> '사용자 차단' 문구를 '내보내기'로 변경했습니다!

Code changes pushed to the remote branch `v2.0.0`

Commit hash:  `72632d0f4a6988cce23de9a22d7a8680a1d805fb`

Check for live-implementation at `https://141.223.82.233:8443/`

![kickoutTextChange](https://user-images.githubusercontent.com/72065079/127079577-9fe2e45a-ccfb-40c7-8dcd-b7c01ddb8e2a.gif)

**Comment by jungheekang** [comment]
문구확인 하였습니다. close 하겠습니다.
