### ISSUE TITLE
[lately][func]라이센스 수 만큼 회의를 생성한 상태에서 로그인한 사용자가 회의참여 시도 시 라이센스 에러 발생  

### ISSUE THREAD

**Issue by jungheekang** [vmeeting-io/vmeeting_issue#211]
[발생현상]
라이센스 수 만큼 회의를 생성한 상태에서 로그인한 사용자가 회의참여 시도 시 라이센스 에러 발생  

[발생일자]
2021-10-08

[재현경로]
- 발생 환경 : 
1. 관리자 콘솔 
2. 사이트 관리 - 라이센스 수 : 2, 회의당 참여자 수 : 100 설정 , 사용자목록 : 5명 등록
3. 사용자 5명 모두 로그인
4. A사용자 A 회의실 생성, B사용자 B회의실 생성
5. C사용자 A 회의실 입장 시 라이센스 오류 발생

**Comment by theun0524** [comment]
수정완료) lately에 적용했습니다.
