### ISSUE TITLE
[flagship][func]모두 음소거 하면 타 참가자화면 알림에 이름이 누락되어 표시됨

### ISSUE THREAD

**Issue by jungheekang** [vmeeting-io/vmeeting_issue#212]
[발생현상]
모두 음소거 하면 타 참가자화면 알림에 이름이 누락되어 표시됨
한국어만 이름이 누락되어 표시됨, 영어는 정상표시됨

[발생일자]
2021-10-08

[재현경로]
- 발생 환경 : 
1. 참가자 목록 
2. 모두음소거 버튼 선택시 

[스크린샷 및 동영상 첨부]
![스크린샷 2021-10-08 오후 12 10 35](https://user-images.githubusercontent.com/87403323/136492435-42cb24c2-ea5e-41fa-b69d-97d012236247.png)

**Comment by sajan-dpnm** [comment]
![image](https://user-images.githubusercontent.com/72065079/136645924-5a35e75f-6164-4a84-ad64-4ef9459cac06.png)

@jungheekang 
Code changes pushed to lately! please confirm

**Comment by jungheekang** [comment]
확인했습니다.
