### ISSUE TITLE
[lately][UI] 회원가입 생일입력 문구 변경 요청

### ISSUE THREAD

**Issue by jungheekang** [vmeeting-io/vmeeting_issue#215]
[발생현상]
 회원가입 생일입력 문구 변경 요청

- Kor
생일정보는 생일모자 AR에 사용되며, 그외에는 사용되지 않습니다.
-> 생일정보는 회의 내 생일 알림, 생일 모자 AR적용에만 사용됩니다.

- Eng
Birthday info will only be used for implementing AR hat.
-> Birthday info will only be used for birthday noti and birthday hat AR in meeting room.

[발생일자]
2021- 10-15

[재현경로]
1. 메인사이트 - 회원가입

[첨부파일]
<img width="419" alt="스크린샷 2021-10-15 오전 11 48 01" src="https://user-images.githubusercontent.com/87403323/137424830-de8f44a9-14d7-48cb-af14-6c374e0a77a4.png">

**Comment by sajan-dpnm** [comment]
Code changes pushed to lately. Please confirm @jungheekang

![image](https://user-images.githubusercontent.com/72065079/137693750-7af3dbc7-9378-43b6-83ae-78f8b81e20ff.png)

![image](https://user-images.githubusercontent.com/72065079/137693842-f7056654-9a44-4d80-9134-35fb73b7d4eb.png)

**Comment by jungheekang** [comment]
good
