### ISSUE TITLE
[lately][UI] 채팅창에 파일업로드 아이콘 추가되어 이모티콘 박스가 옆으로 밀려나있음

### ISSUE THREAD

**Issue by jungheekang** [vmeeting-io/vmeeting_issue#217]
[발생현상]
채팅창에 파일업로드 아이콘 추가되어 이모티콘 박스가 옆으로 밀려나있음

[발생일자]
2021-10-18

[재현경로]
1.  채팅창
2. 이모티콘 버튼

[스크린샷 및 동영상 첨부]
<img width="326" alt="스크린샷 2021-10-18 오후 3 55 11" src="https://user-images.githubusercontent.com/87403323/137682966-a39284fa-f60c-4a65-9590-b803d24b75f4.png">

**Comment by sajan-dpnm** [comment]
Code changes pushed to lately. Please confirm @jungheekang 
![image](https://user-images.githubusercontent.com/72065079/137719338-b311e1f1-a1ee-4b24-a6c1-40ed4be7fe11.png)
