### ISSUE TITLE
[lately][UI] 파일 업로드 시 한국어 깨짐 현상

### ISSUE THREAD

**Issue by jungheekang** [vmeeting-io/vmeeting_issue#218]
[발생현상]
파일 업로드 시 한국어 깨짐 현상

[발생일자]
2021-10-18

[재현경로]
1. 한글로 된 문서 업로드 시

[스크린샷 및 동영상 첨부]
<img width="262" alt="스크린샷 2021-10-18 오후 4 59 25" src="https://user-images.githubusercontent.com/87403323/137691960-c80dac37-66ac-4c29-bee3-a8f8c0fd728c.png">

**Comment by sajan-dpnm** [comment]
Code changes pushed to lately. Please confirm @jungheekang 

![image](https://user-images.githubusercontent.com/72065079/137740614-23071965-abdd-4b61-9c5e-c708db17f0ee.png)
