### ISSUE TITLE
[lately][func] 사파리 브라우저에서 화면공유 시 카메라 ON 설정 불가 요청

### ISSUE THREAD

**Issue by jungheekang** [vmeeting-io/vmeeting_issue#219]
[발생현상]
사파리 브라우저에서 화면공유 시 카메라 ON 설정 불가 요청
(화면공유 시 카메라 비활성화 처리 요청)

[발생일자]
2021-10-25

[재현경로]
1. MAC OS의 사파리 브라우저(safari)
2. 화면 공유 시 카메라ON 불가 요청

**Comment by theun0524** [comment]
lately에 수정/반영했습니다. 사파리 브라우저에서 화면 공유시 카메라 토클 버튼을 숨김.
