### ISSUE TITLE
[lately][UI]APP의 참가자 목록에서 참가자이름 아래 방장 표시 없음

### ISSUE THREAD

**Issue by jungheekang** [vmeeting-io/vmeeting_issue#220]
[발생현상]
참가자 목록에서 참가자이름 아래 방장 표시 없음

[발생일자]
2021-10-25

[재현경로]
1. APP - 회의참석
2. 참석자목록 - 참석자이름 아래 방장표시 없음

[스크린샷 및 동영상 첨부]
APP
![IMG_6E538B8669C7-1](https://user-images.githubusercontent.com/87403323/138669244-779608c8-fc15-461f-9109-f33538455116.jpeg)

WEB
<img width="285" alt="스크린샷 2021-10-25 오후 6 16 43" src="https://user-images.githubusercontent.com/87403323/138669274-182b28af-e708-4608-8a99-99bc6b127139.png">

**Comment by anish9849** [comment]
@jungheekang 
Is it ok to have it on the right side rather than on the bottom ?

<img width="423" alt="40639451-7DEB-4FAF-8A65-2EA6B1771E31" src="https://user-images.githubusercontent.com/85114817/146130453-f80c4b43-4f42-4bf9-875e-564511ac8ce0.png">

**Comment by jungheekang** [comment]
@anish9849 I think it would be better to do it in 2 lines.

**Comment by anish9849** [comment]
@jungheekang Any reason behind it ?

If so, how would you handle the case when name is very long ? 

Having it on the right will look as below:
![image](https://user-images.githubusercontent.com/85114817/146132432-3375cd00-22e0-4c73-865d-ffe21978b928.png)

**Comment by jungheekang** [comment]
![스크린샷 2021-12-15 오후 3 07 40](https://user-images.githubusercontent.com/87403323/146132732-ebc9aa86-850c-444b-a7ce-879e03c936d2.png)

**Comment by jungheekang** [comment]
Just do it like the picture captured above.
You just need to mark it as ... .

**Comment by anish9849** [comment]
OK!!! Please specify the number of characters that you want to show.

**Comment by jungheekang** [comment]
15자리로 해주세요
![스크린샷 2021-12-15 오후 3 17 01](https://user-images.githubusercontent.com/87403323/146133671-382c2e95-325e-480b-86ea-491bf4fd5130.png)
