### ISSUE TITLE
[lately][func] APP 에서 회의 참여시 이름입력 팝업이 입력되지 않아도 X 버튼으로 팝업이 닫힘

### ISSUE THREAD

**Issue by jungheekang** [vmeeting-io/vmeeting_issue#222]
[발생현상]
APP 에서 회의 참여 시 이름입력 팝업이 입력되지 않아도 X 버튼으로 팝업이 닫힘

입력되지 않으면 팝업이 닫히지 않게 해주세요

[발생일자]
2021-11-16

[재현경로]
- 발생 환경 : APP
1. 로그안된 APP 사용자(이름 설정안되있는 상태)
2. 회의 참석
3. 이름 입력 팝업에서 이름 입력하지 않고 닫힘 버튼 시 팝업 닫힘

[스크린샷 및 동영상 첨부]
![IMG_79B94385EB52-1](https://user-images.githubusercontent.com/87403323/141933077-e5239052-b22d-4ce9-938d-125ddb515436.jpeg)

**Comment by anish9849** [comment]
@jungheekang If we do not allow user to close without entering name on this popup, what is the use of this X button ?

**Comment by jungheekang** [comment]
@anish9849 X button은 없애주세요.
