### ISSUE TITLE
[lately][func] 아이폰에서 회의방 접속 후 로그인이 안되는 현상

### ISSUE THREAD

**Issue by sjhan22** [vmeeting-io/vmeeting_issue#23]
[발생현상]
아이폰에서 모든 브라우저 web으로  로그인을 하지 않을 상태로 접속 시 회의방 입장 후에 로그인이 불가능함.
(로그인 버튼을 눌러도 아무런 변화가 없음)

[발생일자]
2021.07.22

[재현경로]
- 발생 환경 : 아이폰 모든 브라우저 web
1. 추가액션 - 이름명(로그인) 
2.
3. 

[스크린샷 및 동영상 첨부]

**Comment by jungheekang** [comment]
MAC, Windows, Android, iOS 동일 발생.
로그인 할 수 있는 버튼으로 생각하는것으로 보여집니다. 
회의실의 설정에서는 로그인 처리화면 팝업 or 로그인 버튼 미표시 또는 비활성화 필요

[로그인 X, 메인화면 설정 팝업]
![스크린샷 2021-07-30 오후 1 36 07](https://user-images.githubusercontent.com/87403323/127600870-3478c507-1f7b-402b-a457-13c9e1d046eb.png)

[로그인 X, 회의실의 설정 팝업]
![스크린샷 2021-07-30 오후 1 38 11](https://user-images.githubusercontent.com/87403323/127601025-dfe2a424-2503-4db4-9d82-0a27e4886087.png)

**Comment by theun0524** [comment]
인증중 문구를 "인증하기"로 변경하였습니다.
로그인 버튼 클릭 시에 로그인 화면으로 이동하고 로그인 후에 다시 이전 회의실로 들어오도록 수정하였습니다.
lately 에서 확인 후 close 바랍니다.

**Comment by jungheekang** [comment]
수정된 문구, 동작 이상없이 동작되는거 확인하였습니다.
