### ISSUE TITLE
[lately][func]DID Operation issue fix request

### ISSUE THREAD

**Issue by jungheekang** [vmeeting-io/vmeeting_issue#230]
[발생현상]
1. account settings - phone Number : 
    ->  Request a change so that it can be saved even if the phone number is deleted(blank)

2. When a non-logged in attendee enters, the login request screen does not appear.

3. admin console - user information - phone number :
    -> Ignore phone number condition and save

[발생일자]
2021-12-03

**Comment by anish9849** [comment]
@jungheekang  Verified ?

**Comment by jungheekang** [comment]
확인했습니다.
