### ISSUE TITLE
[lately][func]

### ISSUE THREAD

**Issue by jungheekang** [vmeeting-io/vmeeting_issue#235]
[발생현상]
로그인 안된 상태에서 링크로 회의 참여 시 로그인 여부(DID) 발생되지 않음
바로 회의에 참여되고 있음

[발생일자]
2021-12-23

[재현경로]
1. 회의 생성 - 링크 복사
2. 로그인 안된 상태의 브라우저에서 링크로 회의 참석 시 로그인 여부 팝업 발생되지 않음

**Comment by theun0524** [comment]
수정완료.
