### ISSUE TITLE
[lately][func]APP에서 회의참가 거부 당하면 메인화면으로 나가지지 않음

### ISSUE THREAD

**Issue by jungheekang** [vmeeting-io/vmeeting_issue#236]
[발생현상]
로비모드에서 APP에서 참가 요청한 참가자가 거부 당하면 메인화면으로 나가지지 않음

[발생일자]
2021-12-23

[재현경로]
1. 회의생성 - 로비모드 활성화
2. APP에서 참가 요청
3. 방장이 회의참가 거부
4. APP에서 메인화면으로 나가지 않음

[스크린샷 및 동영상 첨부]
![IMG_8FE914D3B579-1](https://user-images.githubusercontent.com/87403323/147182569-ea1011e0-30cf-494a-81d6-70a224627da3.jpeg)

**Comment by anish9849** [comment]
Fixed, will upload to testflight on next release.
