### ISSUE TITLE
[lately][func] 회의 생성 후 방장이 퇴장하고 다시 동일한 회의에 참여시 관리자콘솔에 동일한 회의가 또 생성됨

### ISSUE THREAD

**Issue by jungheekang** [vmeeting-io/vmeeting_issue#237]
[발생현상]
회의 생성 후 방장이 퇴장하고 다시 동일한 회의에 참여시 관리자콘솔에 동일한 회의가 또 생성됨

[발생일자]
2021-12-23

[재현경로]
1. A '123' 회의생성 - B,C,D 참가
2. A 회의에서 퇴장
3. A '123' 회의에 재입장
4. 관리자 콘솔 확인 시 123 회의가 생성되어있음

[스크린샷 및 동영상 첨부]
<img width="1352" alt="스크린샷 2021-12-23 오후 12 07 40" src="https://user-images.githubusercontent.com/87403323/147183016-2a9925cc-8317-411e-9f0f-eefab886f855.png">

**Comment by jungheekang** [comment]
flagship 에서도 동일한 증상 발생됩니다.
io 에서는 발생안합니다.

**Comment by theun0524** [comment]
수정완료.

**Comment by jungheekang** [comment]
확인했습니다.
