### ISSUE TITLE
[lately][func]로그인하지 않은 참가자는 Meeting detail - meeting management에 표시 되지 않음

### ISSUE THREAD

**Issue by jungheekang** [vmeeting-io/vmeeting_issue#239]
[발생현상]
로그인하지 않은 참가자는 Meeting detail - meeting management에 표시 되지 않음

[발생일자]
2021-12-28

[재현경로]
1. 로그인하지 않은 참가자 미팅룸에 참석
2. 미팅 종료
3. Meeting detail - meeting management - room name
4. 로그인하지 않은 참가자가 표시 되지 않음(데이터는 빈칸으로 나오고, 참석자는 나와야됨)

[스크린샷 및 동영상 첨부]

**Comment by sajan-dpnm** [comment]
changed. please check at https://vmeeting.maharjansajan.com.np:8443/
