### ISSUE TITLE
[lately][func] 아이폰에서 회의에서 나갈 때 방장 지정이 불가능한 현상

### ISSUE THREAD

**Issue by sjhan22** [vmeeting-io/vmeeting_issue#24]
[발생현상]
아이폰 모든 브라우저 web으로 접속 시 회의에서 나갈 때 디폴트값으로 가장 상단에 있는 참가자가 방장으로 지정되어 있는데 다른사람으로 변경이 불가능함. (다른 사람을 클릭해도 변경되지 않음.)

[발생일자]
2021.07.22

[재현경로]
- 발생 환경 : 아이폰 모든 브라우저 web
1. 회의나가기 - 회의나가기 - 지정 후 나가기
2.
3. 

[스크린샷 및 동영상 첨부]

**Comment by jungheekang** [comment]
[lately][func] 방장이 지정 후 나가기 시도 시 첫 번째 참가자만 선택 가능한 현상 #46와 동일이슈로 
#24번이슈 close하겠습니다.
