### ISSUE TITLE
[lately][func] 보안옵션 - 비밀번호입력필드에 비밀번호입력 후 엔터치면 로비나가지는 현상

### ISSUE THREAD

**Issue by jungheekang** [vmeeting-io/vmeeting_issue#243]
[발생현상]
보안옵션 - 비밀번호입력필드에 비밀번호입력 후 엔터치면 로비나가지는 현상

[발생일자]
2022-06-29

[재현경로]
1. 하단 툴바 -  추가액션 - 보안옵션
2. 비밀번호 설정 - 비밀번호 입력필드에서 엔터 입력 시

**Comment by theun** [comment]
수정완료. lately 서버에 적용해 두었어요.

**Comment by jungheekang** [comment]
확인했습니다.
