### ISSUE TITLE
[lately][func] 참가자 이름이 길면 개인채팅메시지 입력창이 늘어나는 현상

### ISSUE THREAD

**Issue by jungheekang** [vmeeting-io/vmeeting_issue#244]
[발생현상]
참가자 이름이 길면 개인채팅메시지 입력창이 늘어나는 현상

[발생일자]
2022-07-06

[재현경로]
1. 참가자 이름 -> 이름으로 최대길게 입력 
2. 채팅 -> 개인메시지 시 

[스크린샷 및 동영상 첨부]
<img width="373" alt="스크린샷 2022-07-06 오후 5 53 18" src="https://user-images.githubusercontent.com/87403323/177514544-5069da97-bd08-4064-b2b7-987cae3b20c0.png">

**Comment by theun** [comment]
수정완료. lately 서버에 적용해 두었어요.

**Comment by jungheekang** [comment]
확인했습니다.
