### ISSUE TITLE
[lately][func] (방장) 리액션 시 발생되는 알럿창에서 "모두에게 알림음 끄기" 버튼 동작 되지 않음

### ISSUE THREAD

**Issue by jungheekang** [vmeeting-io/vmeeting_issue#245]
[발생현상]
방장일때 최초 리액션 시 발생되는 알럿창에서 "모두에게 알림음 끄기" 버튼 동작 되지 않음

[발생일자]
2022-07-15

[재현경로]
1. 회의생성
2. 리액션 메뉴 - 박수
3.  이 회의에서 리액션 알림을을 끄기로 설정할 수 있습니다. 알럿창 - '모두에게 알림음 끄기' 선택 시 동작 되지 않음

**Comment by theun** [comment]
수정완료. lately 서버에 적용해 두었어요.

**Comment by jungheekang** [comment]
확인했습니다.
