### ISSUE TITLE
[lately][func] 배경적용 후 취소시 오류

### ISSUE THREAD

**Issue by boonjo** [vmeeting-io/vmeeting_issue#25]
[발생현상]

다른 배경 선택후 취소시, 다음에 배경선택에 들어갔을때 카메라 오류

![background_cancel](https://user-images.githubusercontent.com/61446495/126729405-1f7b7dd9-672b-4443-954e-97d696450585.gif)

[발생일자]

2021-07-23

[재현경로]
- 발생 환경 : macOS Chrome, Firefox, Opera, Naver Whale
1. 메인화면 - 로그인 계정명
2. 배경선택 - 특정 배경 선택 - 적용
3. 배경선택 - 다른 배경 선택 - 취소
4. 배경선택 시 미리보기 화면 멈춤현상

**Comment by jungheekang** [comment]
재현경로 업데이트 했습니다.
미리보기 멈춤현상일때 다른 배경 선택시 정상동작 되지만, 현상태에서 회의 시작시 카메라 멈춤현상 발생되어있습니다.

**Comment by theun0524** [comment]
@SangwooRyu 수정 후에 comment 부탁 합니다.

**Comment by SangwooRyu** [comment]
수정하고 현재 lately에 반영했습니다

https://github.com/vmeeting-io/jitsi-meet/commit/1f5b4f9742fb620d2b896babdddcc3f4839c7b34
