### ISSUE TITLE
[lately][func] 사이트 상단 Vmeeting 로고 메인으로 이동 기능 필요  

### ISSUE THREAD

**Issue by jungheekang** [vmeeting-io/vmeeting_issue#33]
[발생현상]
사이트 상단 vmeeting 로고을 클릭하여도 메인으로 이동되지 않음
계정 설정화면에서 메인으로 갈수있는 버튼이 없음
(기존 .io에는 해당 기능있음, 화상회의 중에는 비활성화 처리가 맞는것같습니다. )

[발생일자]
2021-07-23

[재현경로]
- 발생 환경 : 모든 환경
1. 메인화면 - 주요기능
1. 로그인 후 계정 설정 화면

**Comment by huijjj** [comment]
수정하여 lately에 반영했습니다
