### ISSUE TITLE
[lately][func] 로그인된 회원은 무조건 방장 기능 부여되는 현상

### ISSUE THREAD

**Issue by YoungRaeKimm** [vmeeting-io/vmeeting_issue#4]
[발생현상]
로그인한 계정으로 미팅룸에 접속시 방장이 아님에도 불구하고 방장기능이 부여 되었다고 표시됩니다.

[발생일자]
2021-07-22

[재현경로]
- 발생 환경 : iPad OS
1.  미팅룸 생성
2. 다른 id로 로그인
3. 해당 방 접속

[스크린샷 및 동영상 첨부]

- 
<img width="389" alt="스크린샷 2021-07-22 오후 5 36 50" src="https://user-images.githubusercontent.com/33543992/126611396-b3d39447-7bbe-49b0-b75c-e7eb23bafc09.png">

**Comment by tu-nv** [comment]
@theun0524 can you point me the prosody code that process the permission for role host/logged in user/guest user?

**Comment by theun0524** [comment]
@tu-nv Only moderator connect to xmpp server with jwt token if user can create room into vmapi, otherwise user(guest) connect to xmpp server without jwt token.

**Comment by tu-nv** [comment]
@theun this is already implemented in v2.0.0. The issue here is: if 2 users are logged in, then both will join with jwt token and both will be moderator.

**Comment by theun0524** [comment]
@tu-nv it is fixed. Some code is not merged in jitsi-meet/connection.js

**Comment by tu-nv** [comment]
as @theun0524 fixed it, I will close the issue
