### ISSUE TITLE
[lately][UI] 언어가 영어일 때 withdrawl misspelling

### ISSUE THREAD

**Issue by oomuns** [vmeeting-io/vmeeting_issue#41]
[발생현상]
언어가 영어로 설정되어있을 때 회원탈퇴인 withdrawal 이 아닌 오타 withdrawl로 나와있다.
[발생일자]
2021-07-22
[재현경로]
- 발생 환경 :  모든 환경에서
1. 언어를 영어로 설정
2. 계정 설정에 회원탈퇴인 withdrawal 이 오타 나있다.
3.

[스크린샷 및 동영상 첨부]
![misspelling](https://user-images.githubusercontent.com/86105163/126742828-f1f8f782-2c0c-4c44-b92d-7a2e276ee71a.PNG)

**Comment by huijjj** [comment]
수정하여 lately에 반영했습니다

**Comment by oomuns** [comment]
> 수정하여 lately에 반영했습니다

vmeeting.io 에도 동일하게 오타가 존재합니다
