### ISSUE TITLE
[lately][func] E2EE 키 활성화시 음성 & 화면 깨짐

### ISSUE THREAD

**Issue by boonjo** [vmeeting-io/vmeeting_issue#44]
[발생현상]

<img width="1348" alt="e2ee" src="https://user-images.githubusercontent.com/61446495/126746353-569b11fe-0d91-475e-affe-a5bdd1d98c41.png">

[발생일자]

2021-07-23

[재현경로]
- 발생 환경 :  macOS  모든환경
1. 추가액션
2. 보안 옵션
3. E2EE 키

**Comment by jungheekang** [comment]
보안설정에서 E2EE 미표출 - 주간회의 결정

**Comment by theun0524** [comment]
E2EE 기능 비활성화. lately 에서 확인 후 close 부탁 합니다.
