### ISSUE TITLE
[lately][func] 방장이 지정 후 나가기 시도 시 첫 번째 참가자만 선택 가능한 현상

### ISSUE THREAD

**Issue by SangY00n** [vmeeting-io/vmeeting_issue#46]
[발생현상]
방장이 회의 나가기를 통하여 방장 권한을 넘겨 줄 참가자를 선택할 때, 첫 번째 참가자만 선택이 가능하고 다른 참가자는 선택이 불가능합니다.

[발생일자]
2021.07.23

[재현경로]
- 발생 환경 : 윈도우 크롬
회의 나가기-지정 후 나가기-첫 번째 참가자 외의 다른 참가자 선택

[스크린샷 및 동영상 첨부]
![Animation_2021-07-23-16-05-10](https://user-images.githubusercontent.com/85980653/126748284-6adebbff-4c71-4006-9790-6896207e593c.gif)

**Comment by jungheekang** [comment]
[lately][func] 아이폰에서 회의에서 나갈 때 방장 지정이 불가능한 현상 #24 과 동일
#24이슈는 close 하겠습니다.

**Comment by boonjo** [comment]
macOS 모든 브라우저에서도 동일 현상 발생

**Comment by theun0524** [comment]
수정되었습니다. lately에서 확인후 close 부탁합니다.

**Comment by SangY00n** [comment]
정상적으로 수정된 것을 확인하였습니다. issue close 하겠습니다.
