### ISSUE TITLE
[lately][func] 방장 권한을 위임받은 참가자의 '모두에 대해 회의 종료' 정상 동작하지 않음

### ISSUE THREAD

**Issue by SangY00n** [vmeeting-io/vmeeting_issue#47]
[발생현상]
방장 권한을 위임받은 참가자(로그인하지 않은 참가자입니다)가 '모두에 대해 회의 종료' 기능을 사용할 경우 정상 동작하지 않고 자기 자신만 회의에서 나가지는 현상이 발생합니다.

[발생일자]
2021.07.23

[재현경로]
- 발생 환경 :  윈도우 모든 브라우저

tester1: 로그인한 참가자
tester2, tester3, tester4: 로그인 하지 않은 참가자

1. tester1이 회의 생성
2. tester2, tester3, tester4 가 회의실 입장
3. tester1이 tester2에게 방장 권한 위임 후 회의 나가기
4. tester2가 '모두에 대해 회의 종료' 시도
5. tester2만 나가지고 tester3, tester4는 회의에 남아있는 현상 나타남

**Comment by boonjo** [comment]
macOS 모든 브라우저에서 동일현상 발생

**Comment by jungheekang** [comment]
21-08-01 확인 시 현 이슈 동일현상 발생

방을 생성한 방장이 "모두에 대해 회의 종료"는 정상 동작
방장이 위임받은 방장이 "모두에 대해 회의 종료" 시 동작되지 않음.

**Comment by theun0524** [comment]
vmeeting-release-v21.2.0-build-2.apk 버전에서 수정되었습니다.
TestFlight vmeeting 21.2.0(5) 버전에서 수정됨.
확인 후 close 부탁합니다.

**Comment by SangY00n** [comment]
수정이 확인되지 않습니다. 여전히 동일한 현상이 발견됩니다.

**Comment by theun0524** [comment]
android: vmeeting-release-v21.2.0-build-3.apk, iOS: 21.2.0(6) 버전에 수정되었습니다.

**Comment by SangY00n** [comment]
수정을 확인하였습니다. 이슈 닫겠습니다.
