### ISSUE TITLE
[lately][func] 메인화면 배경 선택 기능에서의 오류

### ISSUE THREAD

**Issue by dmsgk724** [vmeeting-io/vmeeting_issue#5]
[발생현상]
메인화면에서 배경 선택 기능을 누르면 아래로 내려가는 스크롤바가 작동하지 않고 
배경 선택 중 화면 공유기능이 작동하지 않음

[발생일자]
2021-07-22

[재현경로]
- 발생 환경 : android chrome, 
1. 메인화면 ->배경 선택
2. 메인화면 ->배경 선택 배경 선택하려 스크롤바를 아래로 내릴시 작동 x
3. 배경 선택후 빠르게 스크롤시 스크롤이 잠시 작동하나 몇 초 후 위로 다시 스크롤바를 올리려 하면 작동하지 않음

[스크린샷 또는 동영상]
https://user-images.githubusercontent.com/85989698/126594212-0aa94fee-fd3a-44b2-bb86-041430e7826e.mp4

**Comment by jungheekang** [comment]
.io 에서는 배경선택 미리보기가 없어 스크롤 발생되지 않음
(andriod, iOS, windows, Mac  브라우저 동일)

**Comment by theun0524** [comment]
수정 완료. lately 에서 확인하고 close 부탁합니다.

**Comment by dmsgk724** [comment]
https://user-images.githubusercontent.com/85989698/127789284-93bc613a-d452-4ad3-a392-d675ff0e2edf.mp4

이런식으로 ui가 나타나는데 스크롤은 되지만, ui가 미완성된 느낌이 있는 것 같습니다

**Comment by theun0524** [comment]
@dmsgk724 수정했는데, css 캐쉬 문제가 있는지 다시 테스트 부탁합니다.

**Comment by dmsgk724** [comment]
Fix된걸 확인하여 이슈를 close합니다
