### ISSUE TITLE
[lately][UI] 안드로이드에서 품질 설정 변경 시 상단 표시가 "HD"로 유지됨 (aud 상태 제외)

### ISSUE THREAD

**Issue by ktm0526** [vmeeting-io/vmeeting_issue#54]
[발생현상]
안드로이드에서 웹 브라우저 사용 시 aud가 아닌 다른 모든 품질 설정 상태에서 상단 표시가 HD로 표기됩니다. 

[발생일자]
2021.07.23

[재현경로]
- 발생 환경 : 안드로이드, 모든 웹 브라우저
1. 회의 접속
2. 추가 액션 - 품질 설정하기 - 저화질, 표준해상도, 고해상도 중 하나로 전환
3. 화면 상단 품질 표기 확인

[스크린샷 및 동영상 첨부]

https://user-images.githubusercontent.com/43801981/126760138-2254d9e3-0b4a-486e-ae8b-d8f918dc63dc.mp4

**Comment by dmsgk724** [comment]
opera브라우저에서는 상단에 LD라는 값이 계속 표시됩니다.
![image](https://user-images.githubusercontent.com/85989698/127106433-e8adc16f-1e6d-47e7-89de-d61cb06086fc.png)

**Comment by sjhan22** [comment]
closed된 #12 오류와 동일한 오류인것 같습니다.

**Comment by jungheekang** [comment]
[lately][UI] 품질 설정 후 회의화면 상단 품질 'AUD'로만 유지되는 현상 #11 동일이슈로 close 합니다.
