### ISSUE TITLE
[lately][func] 이메일 인증 메일이 두 번 보내지는 문제

### ISSUE THREAD

**Issue by jangyoojin** [vmeeting-io/vmeeting_issue#55]
[발생현상]
계정을 만들고 [인증 메일 보내기] 버튼을 처음 누르면 메일이 두 번 보내짐. [인증 메일 보내기] 버튼은 두 번째 클릭부터는 인증 메일이 한 개만 보내짐(즉, 정상작동 함).

[발생일자]
2021.07.26

[재현경로]
- 발생 환경 : 윈도우 크롬, 엣지
1. 회원가입을 통해 새로운 계정 만들기
2. 인증 메일 보내기 버튼 클릭
3. 가입한 메일함으로 가서 온 메일 개수 확인

[스크린샷 및 동영상 첨부]
![image](https://user-images.githubusercontent.com/74976893/126937242-2fb8107f-253e-4a44-a455-e9c01c6869d5.png)

**Comment by SangY00n** [comment]
윈도우 네이버웨일에서도 같은 현상이 나타나는 것을 확인하였습니다.

**Comment by theun0524** [comment]
계정을 만들면 자동으로 이메일 인증 메일이 발송됩니다.
그런데 인증 메일 보내기 버튼을 또 누르기 때문에 인증 메일이 다시 발송된 겁니다.
이슈가 아닙니다.
