### ISSUE TITLE
[lately] 참가자 목록에서의 채팅 차단 기능 추가 및 '사용자 차단' 과 '내보내기' 용어 통일

### ISSUE THREAD

**Issue by SangY00n** [vmeeting-io/vmeeting_issue#57]
[발생현상]
현재 방장이 특정 참가자에 대해서 '채팅 차단'을 하기 위해서는 채팅창에서 _참여자 더보기(...)_ 를 눌러서만 '채팅 차단'이 가능합니다.
따라서 채팅을 차단하고자 하는 참가자가 1회 이상 채팅을 입력하여야만 해당 참가자에 대해 '채팅 차단'이 가능합니다.

'개인 메시지 보내기'나 '내보내기' 기능과 같이 채팅창의 _참여자 더보기(...)_ 에서 뿐만아니라 _참가자 목록_ 에서도 '채팅 차단'을 가능하도록 하는 것이 좋을 것 같습니다.

또한 채팅창의 _참여자 더보기(...)_ 의 '사용자 차단' 과 _참가자 목록_ 의 _더보기(...)_ 의 '내보내기' 의 기능이 동일하므로 용어를 통일하는 것이 좋을 것 같습니다.

[발생일자]
2021.07.26

[스크린샷 및 동영상 첨부]
채팅창의 _참여자 더보기(...)_ 를 눌렀을 때 팝업
![image](https://user-images.githubusercontent.com/85980653/126941806-1b7e07ab-9d86-4b84-a4c9-380fc6b93129.png)

_참가자 목록_ 의 _더보기(...)_ 를 눌렀을 때 팝업
![image](https://user-images.githubusercontent.com/85980653/126942099-00325e44-5c94-407c-9fed-ccb0ddfc0867.png)

**Comment by sajan-dpnm** [comment]
@SangY00n 참가자 목록 에서도 '채팅 차단' 이나 '채팅 허용' 옵션을 추가했습니다. 일단 https://141.223.82.233:8443에서 기능 원하는데로 실행 하고 있는지 아닌지 확인하기 바랍니다!

확인 후, 수정된 코드 v2.0.0 에 push 할 게요!

**Comment by SangY00n** [comment]
I have verified that it works as intended. Should I close this issue?

확인된 내용은 아래와 같습니다.
- 참가자 목록 - 더보기 에 '채팅 차단', '채팅 허용' 옵션 추가됨.
- 채팅창 - 참가자 더보기의 ‘사용자 차단’ 버튼의 이름이 ‘내보내기’ 로 수정됨.

**Comment by jungheekang** [comment]
이슈 해결 확인했습니다. close 하겠습니다.
