### ISSUE TITLE
[lately][func] 채팅으로 한글을 입력할 경우 전의 메세지의 마지막 한글자가 앞에 한번 더 나오는 현상

### ISSUE THREAD

**Issue by YoungRaeKimm** [vmeeting-io/vmeeting_issue#6]
[발생현상]
채팅으로 한글을 입력할 경우 전의 메세지의 마지막 한글자가 앞에 한번 더 나오는 현상 입니다.

[발생일자]
2020-07-22

[재현경로]
- 발생 환경 : iPad OS safari
1. 한글로 채팅 입력
2.
3. 

[스크린샷 및 동영상 첨부]
![IMG_0384](https://user-images.githubusercontent.com/33543992/126612541-45bb0e8b-8869-4ac6-98e1-f2ae85704297.PNG)

**Comment by boonjo** [comment]
비슷한 오류라 여기 thread로 작성합니다.

[발생현상]

한글로 채팅 입력시, 마지막 글자가 한번더 보내지는 현상

<img width="288" alt="korean_chat" src="https://user-images.githubusercontent.com/61446495/126741326-4b2d07bb-4e22-475a-af08-b48a14ef73b2.png">

[발생일자]
2020-07-23

[재현경로]

- 발생 환경 : macOS Chrome

1. 위와 같음

**Comment by YoungRaeKimm** [comment]
아이패드 모든 브라우저에서 동일한 현상 일어납니다.

**Comment by jungheekang** [comment]
- macOS Chrome, Opera, safari 에서 발생되며, 한국어에서만 발생, 영어는 미발생

- Mac OS safari, 웨일, Firefox , windows, android 발생되지 않음

- .io 에서는 발생되지 않는 현상

**Comment by oomuns** [comment]
한글을 친후 backspace 사용시 전에 보낸 글자도 나오는 현상 발생
iPad 모든 브라우저에서 발생


![KakaoTalk_20210728_120158254](https://user-images.githubusercontent.com/86105163/127257117-86fb46ed-b5f5-4061-97f5-e7822d81f2db.gif)

**Comment by sajan-dpnm** [comment]
@jungheekang https://141.223.82.233:8443 에서 코드 수정 했습니다. 문제가 해결 되는지 한번 확인 하기 바랍니다

**Comment by jungheekang** [comment]
@sajan-dpnm 해당 URL에 접근이 되지 않습니다. 확인부탁드립니다.

**Comment by sajan-dpnm** [comment]
아, 미안합니다. 포스텍 교내에서 만 접속 가능하니까, 다른 머신에서 운영하고 알려 드릴게요!

**Comment by sajan-dpnm** [comment]
@jungheekang https://vmeeting1.postech.ac.kr:8443 에서 한번 확인 해 보세요!

**Comment by jungheekang** [comment]
@sajan-dpnm 해당 URL에서 정상동작 확인하였습니다. 감사합니다.
