### ISSUE TITLE
[lately][func] 회의실에 패스워드가 설정된 상태에서 라이브 스트리밍이 시작되지 않는 현상

### ISSUE THREAD

**Issue by SangY00n** [vmeeting-io/vmeeting_issue#60]
[발생현상]
방장이 회의실에 패스워드를 설정할 경우 라이브 스트리밍 기능 사용 시 라이브 스트리밍이 시작되지 않습니다.

이 이슈는 #9 이슈와 비슷한 이슈로 보입니다.

[발생일자]
2021.07.26

[재현경로]
- 발생 환경 : 윈도우 크롬
1. 방장이 ...추가 액션-보안 옵션-패스워드 추가 를 통해 회의실에 패스워드를 설정
2. 방장이 ...추가 액션-라이브 스트리밍 시작 을 통해 라이브 스트리밍 시작

[스크린샷 및 동영상 첨부]
아래의 알럿이 지속적으로 떠있으면서 라이브 스트리밍이 시작되지 않습니다.
![image](https://user-images.githubusercontent.com/85980653/126947862-8cfdd779-dcf7-46bb-9728-4220d09f6090.png)

일정 시간이 지나면 아래의 알럿이 뜨며 라이브 스트리밍 시작 실패를 알립니다.
![image](https://user-images.githubusercontent.com/85980653/126955382-a404e352-933f-45ce-9501-83f4462e6856.png)

**Comment by tu-nv** [comment]
@SangY00n as #9 is fixed, can you verify whether this issue is also fixed?

**Comment by SangY00n** [comment]
This issue has also been fixed. I will close this.
