### ISSUE TITLE
[lately][func] 윈도우 Chrome 에서 화면 공유 시 배경이 사라지는 현상

### ISSUE THREAD

**Issue by oomuns** [vmeeting-io/vmeeting_issue#64]
[발생현상]
화면 공유 시 카메라 배경 설정이 사라지는 현상

[발생일자]
2020-07-26
[재현경로]
- 발생 환경 :  윈도우 Chrome
1.  카메라 배경 설정
2. 화면 공유 시 배경이 사라짐
3. 

[스크린샷 및 동영상 첨부]

![image](https://user-images.githubusercontent.com/86105163/126961787-85cf6b1b-96f0-47d1-8f4c-79052dc96783.png)
화면 공유 전 정상적으로 배경 작동

![image](https://user-images.githubusercontent.com/86105163/126961825-9af94865-7494-40b6-9b71-25bd4b858e2d.png)
화면 공유 후 배경이 사라짐

**Comment by jungheekang** [comment]
네이버 웨일 브라우저는 하단 작은 본인영상 뷰 박스가 표출되지 않음

**Comment by jungheekang** [comment]
#122. 동일 현상으로 close 합니다.
