### ISSUE TITLE
[lately][func] 로비 모드 활성화 시 방장 권한을 가진 참여자의 접속자 통계 이름이 not_found 로 표시되는 현상

### ISSUE THREAD

**Issue by SangY00n** [vmeeting-io/vmeeting_issue#65]
[발생현상]
회의 참여자 중 방장 권한을 가지고 있는 참여자가 로비 모드를 활성화할 경우, 방장 권한을 가지고 있는 모든 참여자들의 접속자 통계 이름이 'not_found' 로 표시됩니다.

[발생일자] 
2021.07.26

[재현경로]
- 발생 환경 : 모든 브라우저
1. 방장이 추가 액션(...) - 보안 옵션 - 로비 활성화 를 통하여 로비 모드를 활성화
2. 추가 액션(...) - 접속자 통계 에서 참여자들의 이름 확인

[스크린샷 및 동영상 첨부]

tester1, tester2 : 방장 권한을 가지고 있는 참여자 (로그인한 참여자라서 방장 권한 획득)
tester3 : 방장 권한을 부여받은 참여자 (tester1이 '방장 위임'을 통하여 tester3에게 방장 권한 부여)
tester4 : 방장 권한을 가지고 있지 않은 참여자

[로비 모드 활성화 전]
![image](https://user-images.githubusercontent.com/85980653/126961941-f60284ec-84b9-4fc7-905e-13214935ae8e.png)

[로비 모드 활성화 후]
![image](https://user-images.githubusercontent.com/85980653/126962104-9a197dfe-01fa-455a-8e6b-c7dfeba4ba8b.png)

방장 권한을 가지고 있던 tester1, tester2, tester3 만 접속자 통계 이름이 'not_found' 로 표시되고,
tester4 의 접속자 통계 이름은 그대로 표시됩니다.

**Comment by theun0524** [comment]
@tu-nv I checked this. This issue caused by mod_participant_log:on_broadcast_presence. Please check this issue.

**Comment by theun0524** [comment]
@tu-nv It fixed. The hook function in mod_participant_log.erl should run only for XMPP_MUC_DOMAIN.
수정됨. lately 에서 확인후 close 부탁합니다.

**Comment by tu-nv** [comment]
As Taehwan fixed it, I will close the issue
