### ISSUE TITLE
[lately][func] 파이어폭스 웹 브라우저에서 녹화를 하면 시간이 지난 후에 자동으로 녹화가 종료됨

### ISSUE THREAD

**Issue by dmsgk724** [vmeeting-io/vmeeting_issue#68]
[발생현상]
파이어 폭스 브라우저에서 녹화를 하면 시간이 지난 후에 자동으로 녹화가 종료된다.

[발생일자]
2021-07-26
[재현경로]
- 발생 환경 : android firfox
1. 기타 설정- 녹화 시작
2. 녹화 시작을 누를 시 녹화가 시작된다는 메시지가 뜨면서 화면 상단에 rec라는 빨간색 버튼이 생기고 녹화가 된다.
3. 시간이 지나고 자동으로 녹화가 종료 되며 메일이 전송된다.
4. recording failed to start라는 알림이 온다.
5. 전송된 메일에는 종료되기 직전까지의 영상이 나온다.

[스크린샷 또는 동영상]

![image](https://user-images.githubusercontent.com/85989698/126983380-b60634ce-c453-4b73-bc56-58c8efb782d9.png)

**Comment by tu-nv** [comment]
@theun0524 do we also support android firefox?

**Comment by dmsgk724** [comment]
+ android 네이버 웨일과, microsoft edge에서는 녹화시작이 안되면서 녹화되었다는 메일이 엄청 많이 발송됩니다. 막상 링크를 누르면 아무것도 뜨지 않습니다.

**Comment by jungheekang** [comment]
@dmsgk724 재현이 안되는데 재 확인 부탁드립니다.

**Comment by dmsgk724** [comment]
재현 되지 않아 issue를 close합니다
