### ISSUE TITLE
[lately][UI] 메인화면 계정설정 화면의 풀다운 메뉴에 배경선택 및 설정 메뉴가 없음

### ISSUE THREAD

**Issue by ktm0526** [vmeeting-io/vmeeting_issue#7]
[발생현상]
회의 생성 메인화면에서 계정설정 화면으로 넘어간 후 우측 상단의 풀다운 메뉴를 열어보면 주요기능, 계정 설정, 로그아웃 메뉴만 존재합니다.

[발생일자]
2021.07.22

[재현경로]

- 발생 환경 : 안드로이드, 모든 브라우저

1. 메인 화면
2. 계정 설정
3. 풀다운 메뉴 터치

[스크린샷 및 동영상 첨부]

![image](https://user-images.githubusercontent.com/43801981/126612426-7794c72f-05c8-4d2e-b233-24f4160b2e2a.png)

**Comment by jungheekang** [comment]
설정메뉴는 계정설정에서는 미표출되고 메인화면에서의 드롭다운에서만 표출되는게 컨셉으로 보입니다.
해당 이슈는 close 하겠습니다.
