### ISSUE TITLE
[lately][func] 네이버웨일 브라우저에서 키보드 단축키 사용 불가

### ISSUE THREAD

**Issue by SangY00n** [vmeeting-io/vmeeting_issue#72]
[발생현상]
WindosOS 내의 네이버웨일 브라우저에서 키보드 단축키 사용이 불가능합니다.

[발생일자]
2021.07.27

[재현경로]
- 발생 환경 : WindowOS 네이버웨일
1. 회의실 내에서 단축키 사용 시도

**Comment by boonjo** [comment]
발생 환경 macOS 네이버 웨일에서도 똑같은 상황 발생합니다.

**Comment by SangY00n** [comment]
현재 네이버 웨일 브라우저에서 단축키 사용이 가능한 것을 확인하였습니다. 이슈 close 하겠습니다.
