### ISSUE TITLE
[lately][UI] 회원탈퇴 alert 메세지 문구 

### ISSUE THREAD

**Issue by YoungRaeKimm** [vmeeting-io/vmeeting_issue#73]
[발생현상]
회원탈퇴 alert 메세지가 올바르지 않게 뜨는 현상입니다.

[발생일자]
2021-07-27

[재현경로]
- 발생 환경 : 아이패드 firefox
1. 로그인
2. 계정설정
3. 회원탈퇴

[스크린샷 및 동영상 첨부]
![IMG_0404](https://user-images.githubusercontent.com/33543992/127100491-84ef69d2-d715-43b6-b2eb-0e7794870e98.PNG)
![IMG_0403](https://user-images.githubusercontent.com/33543992/127100505-cbc5b696-7399-4372-8780-48b21934231c.PNG)

**Comment by huijjj** [comment]
수정하여 lately에 반영했습니다
