### ISSUE TITLE
[lately][UI]로비 모드에서 대기 중 회의종료 알럿 문구 변경 필요

### ISSUE THREAD

**Issue by jungheekang** [vmeeting-io/vmeeting_issue#75]
[발생현상]
로비모드에서 참여 대기 중 회의종료되면 참여자 화면의 회의 종료 알럿팝업 문구 변경 필요
"dialog.lobby room closed.   ->   호스트가 회의를 종료했습니다."

[발생일자]
2021-07-27

[재현경로]
- 발생 환경 : 모든 환경
1. 회의 생성 - 보안옵션 - 로비모드 활성화
2. 참여자가 해당 회의실 입장 - 미팅참여신청
3. 방장 회의 종료 시 참여자 화면 알럿 팝업 확인

[스크린샷 및 동영상 첨부]
![image](https://user-images.githubusercontent.com/87403323/127104300-b4a8b3ec-39e1-4d49-8a20-36e8beb81cba.png)

**Comment by theun0524** [comment]
수정됨. lately 에서 확인후 close 부탁합니다.

**Comment by jungheekang** [comment]
문구 변경 확인되었습니다. close 합니다.
