### ISSUE TITLE
[lately][func]android 판서에서 hand기능 작동 오류

### ISSUE THREAD

**Issue by dmsgk724** [vmeeting-io/vmeeting_issue#76]
[발생현상]
android 판서에서 hand기능이 작동하지 않는다.

[발생일자]
2021-07-27

[재현경로]
- 발생 환경 : android 모든 웹브라우저
1. 기타 설정- 판서 열기
2. hand기능으로 판서 내용을 움직여서 보이는 위치가 다르게 하려고 해도 기능이 작동하지 않는다.
3. hand기능을 한번 더 눌러서 나타나는 move는 작동한다.

[스크린샷 및 동영상 첨부]

**Comment by jungheekang** [comment]
[lately][UI] 판서의 hand 기능 작동 안되는 현상 #22 동일이슈로 close합니다.
