### ISSUE TITLE
[lately][UI] 회원 탈퇴 버튼 클릭 시 탈퇴 확인 메시지 출력 오류

### ISSUE THREAD

**Issue by SangY00n** [vmeeting-io/vmeeting_issue#77]
[발생현상]
계정 설정에서 회원 탈퇴 버튼 클릭 시 탈퇴 확인 메시지가 정상적으로 출력 되지 않습니다.

'withdrawl.checkMsg' 와 'withdrawl.success' 로 출력됩니다.

[발생일자]
2021.07.27

[재현경로]
- 발생 환경 : 모든 브라우저
1. 계정 설정
2. 회원 탈퇴 버튼 클릭
3. [Warning!] 창 확인 버튼 클릭

[스크린샷 및 동영상 첨부]

![image](https://user-images.githubusercontent.com/85980653/127106947-31854e2f-02d8-4c80-9527-3d8ad94c666a.png)

![Animation_2021-07-27-15-34-59](https://user-images.githubusercontent.com/85980653/127107202-6f31506f-5a96-4460-8c5e-e3dc7b41e429.gif)

**Comment by jungheekang** [comment]
[lately][UI] 회원탈퇴 alert 메세지 문구 #73 동일이슈로 close 합니다.
