### ISSUE TITLE
[lately][func] 회의 이름 적는 칸 클릭 후 메인화면에서 배경 선택 시 나타나는 오류

### ISSUE THREAD

**Issue by dmsgk724** [vmeeting-io/vmeeting_issue#8]
[발생현상]
회의 이름을 적는 칸에 커서를 두면 키보드가 화면에 나타나있는 상태 이러한 상태에서 메인화면->배경선택을 누르면 기능 전체가 동작하지 않음
비디오 자체가 움직이지 않는 경우도 있고 비디오는 움직이지만 화면이 절반 잘려서 나오는 경우도 있음

[발생일자]
2021-07-22

[재현경로]
- 발생 환경 : android chrome, 
1. 회의 이름 적는 칸 클릭 
2. 메인화면 ->배경 선택

[스크린샷 또는 동영상]

https://user-images.githubusercontent.com/85989698/126612632-ff14e1a4-0346-4a7e-8b65-0ed7455b1c83.mp4

**Comment by jungheekang** [comment]
[lately][func] 메인화면 배경 선택 기능에서의 오류 #5 동일 이슈로 close하겠습니다.
