### ISSUE TITLE
[lately][func] Youtube 비디오 공유 안되는 현상

### ISSUE THREAD

**Issue by YoungRaeKimm** [vmeeting-io/vmeeting_issue#82]
[발생현상]
youtube 비디오 공유가 안되는 현상입니다. 유튜브 링크를 삽입하면 '동영상을 볼 수 없습니다.'라고 나옵니다.

[발생일자]
2021-07-29

[재현경로]
- 발생 환경 : 아이폰 11 테스트 어플
1. ... 버튼 누르기
2. 추가옵션 누르기
3.  YouTube 비디오 시작
4.  링크 삽입

[스크린샷 및 동영상 첨부]
![IMG_8241](https://user-images.githubusercontent.com/33543992/127441811-2d44c485-e132-4278-a1f8-3288496136b8.PNG)

**Comment by boonjo** [comment]
추가로 브라우저에서 YouTube 공유시,

![IMG_A56873DE9DD7-1](https://user-images.githubusercontent.com/61446495/127445391-70b0d789-6d31-4dfb-8a37-65bc16c23f66.jpeg)

이런 화면이 어플속 화면에서 뜬다.

**Comment by jungheekang** [comment]
재생동작 수정이 어려울 경우
app에선 youtube공유 메뉴 비활성화, 
브라우저에서 유튜브공유 시 app에 출력되는 문구 수정필요

**Comment by theun0524** [comment]
vmeeting-release-v21.2.0-build-2.apk 버전에서 youtube, live streaming 메뉴 제거하였습니다.
app 출력 문구를 어떻게 수정하는게 좋을지 의견 부탁합니다.

**Comment by jungheekang** [comment]
@theun0524 "어플리케이션에선 호스트가 공유한 YouTube를 재생할수 없습니다." 문구는 어떨까요?
('어플리케이션' or 'App' or 'Vmeeting App')

**Comment by theun0524** [comment]
android: vmeeting-release-v21.2.0-build-3.apk, iOS: 21.2.0(6) 버전에 수정되었습니다.
현재는 YouTube 비디오 공유 동작됩니다.
