### ISSUE TITLE
[lately][UI] 판서아이콘과 vmeeting 상단이미지와 곂침

### ISSUE THREAD

**Issue by jungheekang** [vmeeting-io/vmeeting_issue#84]
[발생현상]
판서열기하면 판서아이콘과 vmeeting 상단이미지와 곂쳐보여지는 현상

[발생일자]
2021-07-21

[재현경로]
- 발생 환경 : 전체 환경
1. 임의 회의생성
2. …(추가액션) - 판서열기

[스크린샷 및 동영상 첨부]
<img width="899" alt="스크린샷 2021-07-29 오후 3 25 39" src="https://user-images.githubusercontent.com/87403323/127442365-af1b5237-9acf-42ec-800e-21881b3b301d.png">

**Comment by theun0524** [comment]
수정됨. lately에서 확인후 close 부탁합니다.

**Comment by jungheekang** [comment]
UI 정상 동작 확인했습니다.
