### ISSUE TITLE
[lately][func] 녹화가 시작되지 않는 현상

### ISSUE THREAD

**Issue by jangyoojin** [vmeeting-io/vmeeting_issue#87]
[발생현상]
안드로이드 앱 환경에서 녹화가 시작되지 않습니다. 아래와 같은 환경에서 확인 버튼이 눌리지 않는 것 같습니다.

[발생일자]
2021.07.29

[재현경로]
- 발생 환경 : 안드로이드 태블릿 앱
1. 방장이 안드로이드 태블릿 앱으로 접속하고 녹화 시작 버튼 누르기
2. 확인 버튼 누르기 -> 확인 버튼이 작동하지 않음

[스크린샷 및 동영상 첨부]
![image](https://user-images.githubusercontent.com/74976893/127443810-6639115c-7e80-4713-a226-b239f781eed0.png)

**Comment by jungheekang** [comment]
태블릿에서만 '녹화시작' 메뉴가 표출되고 있습니다.

**Comment by theun0524** [comment]
로그인 한 상태에서는 녹화 시작 메뉴가 표시되는게 정상입니다.
vmeeting-release-v21.2.0-build-2.apk 버전에서 아이콘을 웹과 동일하게 수정했습니다.
TestFlight vmeeting 21.2.0(5) 버전에서 아이콘을 웹과 동일하게 수정했습니다.
이전 버전에서도 녹화 시작 오류는 없습니다.
새 버전에서 확인 후 close 부탁합니다.
