### ISSUE TITLE
[lately][UI] 방장이 로비에 있는 참여자 회의 참여 허용 시 다른 참여자들에게 잘못된 문구가 출력되는 현상

### ISSUE THREAD

**Issue by SangY00n** [vmeeting-io/vmeeting_issue#88]
[발생현상]
방장이 로비에 있는 참여자의 회의 참여를 허용하였을 때 회의에 참여하고 있던 다른 참여자들에게 잘못된 문구가 출력되는 현상이 발견됩니다.

예를 들어 방장 권한을 가지고 있는 '방장1'이 로비에 있던 '참여자1'의 회의 참여를 허용하였을 때, 

다른 참여자들에게 "참여자1님이 방장1님의 참여를 허용했습니다." 라는 문구가 알럿됩니다.

[발생일자]
2021.07.29

[재현경로]
- 발생 환경 : 아이폰 8+, 아이패드 7세대 테스트 어플 / 모든 브라우저
1. 방장이 추가 액션(...) - 보안 옵션을 통해 로비 모드 활성화
2. 새로운 참여자가 미팅 참여 신청
3. 방장이 수락
4. 기존에 회의실에 있던 다른 참여자가 '참여 허용' 알럿 문구 확인

[스크린샷 및 동영상 첨부]
아래는 '아이패드'가 '컴퓨터'의 회의 참여를 허용하였을 때, 아이폰에서 확인된 알럿 문구입니다.
![image](https://user-images.githubusercontent.com/85980653/127445842-18ba909f-5395-4076-9f86-844d73bf1bc4.png)

**Comment by jungheekang** [comment]
방장 권한을 가지고 있는 '방장1'이 로비에 있던 '참여자1'의 회의 참여를 허용하였을 때,
다른 참여자들에게 "참여자1님이 방장1님의 참여를 허용했습니다." 라는 문구가 표시됩니다.
-> "방장1"님이 "참여자1"님의 참여를 허용했습니다.  수정 필요("승인자"와 과 "승인요청자"가 문구 위치가 바뀜 )

**Comment by theun0524** [comment]
@tu-nv I think this issue caused by mod_muc_lobby_rooms.erl. Please check this issue.

**Comment by huijjj** [comment]
방금 tu가 말해줬는데 이게 영어는 participant is allowed by moderator 식으로 수동태로 쓰였으나, 한글은 능동태로 작성되어 있어 순서가 뒤 바낀 것 같습니다. 확인해보고 고치겠습니다.

**Comment by tu-nv** [comment]
thank you @huijjj

**Comment by tu-nv** [comment]
fixed by @huijjj
