### ISSUE TITLE
[lately][func] 추가 액션의 모두 음소거, 모든 카메라 끄기가 동작하지 않음

### ISSUE THREAD

**Issue by jangyoojin** [vmeeting-io/vmeeting_issue#89]
[발생현상]
갤럭시탭 S7, 갤럭시S10의 앱으로 접속하고 윈도우 크롬 웹으로 접속했을 때,
갤럭시탭S7이 방장일 때와 pc가 방장일 때 둘 다 [모두 음소거] [모든 카메라 끄기]가 동작하지 않음.
앱 유저 사이에서 음소거 또는 카메라를 끄는 것과 앱 유저와 pc 유저 사이에서 서로의 음소거 또는 카메라를 끄는 것이 작동하지 않는 것으로 보임

[발생일자]
2021.07.29

[재현경로]
- 발생 환경 : 안드로이드 앱(사용 기기: 갤럭시탭S7, 갤럭시S10) 
1. 갤럭시탭 S7, 갤럭시S10의 앱으로 접속하고 윈도우 크롬 웹으로 접속
2. 갤럭시탭 S7이 방장인 상황에서 추가 액션 - [모두 음소거] 또는 [모든 카메라 끄기] 클릭
3. 아무런 변화가 없음을 알 수 있음
4. 동일한 환경에서 pc가 방장일 때에 대해 2번을 실행

**Comment by jangyoojin** [comment]
pc가 방장일 때, 참가자-> ...더보기-> 카메라 끄기 또는 다른 사람 모두 음소거 기능도 앱의 카메라 또는 마이크를 제어하지 못합니다

**Comment by theun0524** [comment]
vmeeting-release-v21.2.0-build-2.apk 버전에서 수정됨.
TestFlight vmeeting 21.2.0(5) 버전에서 수정됨.
확인 후 close 부탁합니다.

**Comment by jangyoojin** [comment]
새로운 버전에서 pc가 방장일 때는 폰과 태블릿 사용자에 대해 모두 음소거, 모든 카메라 끄기 기능이 정상 작동하지만, 폰 또는 태블릿이 방장일 때는 pc와 다른 모바일 기기에 대해 모두 음속, 모든 카메라 끄기 기능이 작동하지 않습니다.

**Comment by theun0524** [comment]
android: vmeeting-release-v21.2.0-build-3.apk, iOS: 21.2.0(6) 버전에 수정되었습니다.

**Comment by jangyoojin** [comment]
정상 동작하는 것을 확인했습니다

**Comment by jangyoojin** [comment]
vmeeting-release-v21.3.0 버전에서 동일한 문제가 발생합니다. pc 사용자가 방장일 때는 추가 액션 - [모두 음소거] [모든 카메라 끄기] 버튼이 정상 동작하지만, 앱 사용자가 방장일 때는 추가 액션의 [모두 음소거] [ 모든 카메라 끄기] 기능이 동작하지 않습니다.

**Comment by jangyoojin** [comment]
vmeeting-release-v21.3.0-build-1 버전에서 정상 동작하는 것을 확인했습니다.
