### ISSUE TITLE
[lately][func] 회의실에 패스워드가 설정된 상태에서 녹화가 시작되지 않는 현상

### ISSUE THREAD

**Issue by SangY00n** [vmeeting-io/vmeeting_issue#9]
[발생현상]
방장이 회의실에 패스워드를 설정할 경우 회의 녹화 기능 사용 시 녹화가 시작되지 않습니다.

[발생일자]
2021.07.22

[재현경로]
- 발생 환경 : 윈도우 크롬
1. 방장이  ...추가 액션-보안 옵션-패스워드 추가 를 통해 회의실에 패스워드를 설정
2. 방장이 ...추가 액션-녹화 시작

[스크린샷 및 동영상 첨부]
아래의 알럿이 지속적으로 떠있으면서 영상 다운로드 url 메일이 계속 발송됩니다.
![image](https://user-images.githubusercontent.com/85980653/126612235-6181bd2b-933b-4f83-90f5-3aafc6b861bb.png)

다운로드 url 메일 스크린샷 (다운로드 버튼이 있어야 할 자리에 버튼이 없습니다.)
![image](https://user-images.githubusercontent.com/85980653/126612453-c7693495-55bf-4a60-a34d-80851f1a921d.png)

![image](https://user-images.githubusercontent.com/85980653/126612563-4798894c-bae7-4ee4-a26d-6b16ca9d53a6.png)

일정 시간이 지나면 레코딩을 시작하지 못했다는 알럿이 뜹니다.
![image](https://user-images.githubusercontent.com/85980653/126612886-60bb2df1-8386-4e9d-8099-5e20c40b1891.png)

**Comment by jungheekang** [comment]
.io 에서는 발생되지 않음

**Comment by tu-nv** [comment]
fixed by enabling mod_jibri_pass
