### ISSUE TITLE
[lately][UI] 두명의 방장이 있을 시 새로운 모바일 기기에서 접속 안된다

### ISSUE THREAD

**Issue by dmsgk724** [vmeeting-io/vmeeting_issue#90]
[발생현상]
같은 이메일을 사용하는 유저가 각각 모바일 앱과 웹 브라우저로 접속할 시 웹 브라우저에서 접속자 통계를 볼 시 방장이 2명인 상태가 된다, 이 때 새로운 기기로 방에 접속 할 시 참가할 수 없음

[발생일자]
2021-07-29

[재현경로]
- 발생 환경 : 
1. 같은 이메일로 로그인한 유저가 동시에 방에 접속(윈도우 크롬, ios)
2. Android 모바일 앱으로 동일한 방에 접속 시도
3. 호스트를 기다리라는 알림이 뜬 후 연결이 끊어졌다는 알림 뜸

[스크린샷 및 동영상 첨부]
![Screenshot_20210729-162508_Vmeeting](https://user-images.githubusercontent.com/85989698/127450281-bba1dc19-0194-4060-a306-ffb11560ac07.jpg)

![Screenshot_20210729-162455_Vmeeting](https://user-images.githubusercontent.com/85989698/127450172-ddbc43e3-bf63-4328-91c6-08880f6a6854.jpg)

**Comment by theun0524** [comment]
재현 안됨. 상세한 재현 경로 설명 부탁합니다.

**Comment by dmsgk724** [comment]
같은 방법으로 다른 날짜에 재현 하였을 때 나타나지 않았고 여러 번 더 시도한 결과 재현되지 않아 이슈를 close합니다.
