### ISSUE TITLE
[lately][func] app에서 참가자 이름이 표출 되지 않음

### ISSUE THREAD

**Issue by jungheekang** [vmeeting-io/vmeeting_issue#96]
[발생현상]
app에서 참여자들 영상 하단에 참가자 이름이 표출 되지 않아 누가 누구인지 파악되지 않음

(카메라가 꺼진 참가자만 이름 표시됨)
(휴대기기 web에서는 참가자 모두 잘 표시됨)

[발생일자]
2021-07-31

[재현경로]
- 발생 환경 : android, iOS app
1. android app에서 회의실 생성
2. iOS app, android app에서 참여 시 참여자영상 확인

[스크린샷 및 동영상 첨부]
![KakaoTalk_Photo_2021-07-31-19-14-58](https://user-images.githubusercontent.com/87403323/127736744-37d0f375-345d-4e49-83e3-0a85b0c0e8ab.jpeg)

**Comment by theun0524** [comment]
vmeeting-release-v21.2.0-build-2.apk 버전에서 수정됨.
TestFlight vmeeting 21.2.0(5) 버전에서 수정됨.
확인 후 close 부탁합니다.

**Comment by jungheekang** [comment]
and : v21.2.0, iOS : v21.2.0(5)에서 확인하였습니다.
