### ISSUE TITLE
[lately][func] 회의 이름에 한국어가 포함된 경우, '모두에 대해 회의 종료' 비정상적으로 작동

### ISSUE THREAD

**Issue by SangY00n** [vmeeting-io/vmeeting_issue#97]
[발생현상]
새로운 회의 생성 시 회의 이름을 한국어가 포함된 이름으로 설정할 경우, 방장이 '모두에 대해 회의 종료' 기능을 사용하였을 때 방장 혼자 회의실에서 나가집니다.

PC 사용자가 방장일 때, 2.0 ver 어플 사용자가 방장일 때 모두 발생하는 현상입니다.

[발생일자]
2021.08.02

[재현경로]
- 발생 환경 : 윈도우 모든 브라우저, iOS 어플, 안드로이드 어플에서 확인 완료
1. 한국어로 회의 이름을 설정하여 회의실 생성
2. 다른 참여자 해당 회의실 입장
3. 방장이 '모두에 대해 회의 종료' 시도
4. 방장만 나가지는 현상 발생

[스크린샷 및 동영상 첨부]
회의 생성 시 회의 이름에 한국어를 포함
![image](https://user-images.githubusercontent.com/85980653/127824951-f6d7728b-3b52-4e3e-86e5-253ea41b95fb.png)

**Comment by theun0524** [comment]
@tu-nv In process_event function on mod_site_license.lua, Room should be converted to uri encoded form.

**Comment by tu-nv** [comment]
thank you @theun0524. This issue is fixed in latest v2.0.0
