### ISSUE TITLE
[lately][func] 앱에서 캡차 기능 동작 안함

### ISSUE THREAD

**Issue by jangyoojin** [vmeeting-io/vmeeting_issue#98]
[발생현상]
휴대폰으로 안드로이드 앱을 실행할 경우, 로그인 5회 이상 잘못 입력해도 캡차 동작하지 않음. 아래 사진과 같이 5회 이상 연속으로 잘못된 비밀번호를 입력해도 캡차가 보이지 않음. 태블릿에서는 정상 동작 함.

[발생일자]
2021.08.02

[재현경로]
- 발생 환경 : 휴대폰 안드로이드 앱
1. 휴대폰으로 브이미팅 앱 접속
2. 새로운 회의 생성 -> 팝업 창의 확인 클릭
3. 로그인 페이지에서 5회 이상 잘못된 로그인 정보 입력

[스크린샷 및 동영상 첨부]
![image](https://user-images.githubusercontent.com/74976893/127827247-0c855481-1e16-4010-a0fe-8e75c4e08f3e.png)
![image](https://user-images.githubusercontent.com/74976893/127827269-50103cb2-4baa-4e94-8b28-51de37d6355b.png)

**Comment by anish9849** [comment]
Could you please send me the android application(.apk) file ?

**Comment by SangY00n** [comment]
아이폰과 아이패드 앱에서도 같은 현상이 발견됩니다.

**Comment by anish9849** [comment]
Working well at my device(Android 10). 

![Screenshot_20210802-174204_Vmeeting](https://user-images.githubusercontent.com/85114817/127832583-57ff2df5-961c-463e-8639-dc65271ad9d4.jpg)

Looking at the screenshots it seems like it is not a wrong password. I seems like you guys are trying with the wrong username.

**Comment by jangyoojin** [comment]
정상작동 함을 확인했습니다
